In [1]:
import cv2
import numpy as np

img = cv2.imread('./img/shapes.png')
# cv2.imshow('img', img)
img2 = img.copy()
# cv2.imshow('img2', img)

imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# cv2.imshow('imgray', img)

# 스레시홀드로 바이너리 이미지로 만들어서 검은색 배경에 흰색 전경으로 반전
ret, imthres = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
# cv2.imshow('imthres', imthres)

# 가장 바깥쪽 컨투어에 대해 모든 좌표 반환
im2, contour, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
print(contour)
# print(len(contour))
# print(hierarchy)

# 가장 바깥쪽 컨투어에 대해 꼭짓점 좌표만 반환
im2, contour2, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
# print(len(contour2))
# print(hierarchy)

# 모든 좌표를 갖는 컨투어 그리기, 초록색
cv2.drawContours(img, contour, -1, (0, 255, 0), 4)

# 꼭짓점 좌표만을 갖는 컨투어 그리기, 초록색
cv2.drawContours(img2, contour2, -1, (0, 255, 0), 4)

# print(len(contour[0]))
# print(len(contour2[0]))
# print(len(contour[1]))
# print(len(contour2[1]))
# print(len(contour[2]))
# print(len(contour2[2]))

# 316
# 152
# 448
# 4
# 336
# 225

# 컨투어의 모든 좌표를 작은 파란색 점(원)으로 표시
for i in contour :
    for j in i :
#         print(j)
#         print(j[0])
#         print(tuple(j[0]))
        cv2.circle(img, tuple(j[0]), 1, (255, 0, 0), -1)

# 컨투어의 꼭짓점 좌표를 작은 파란색 점(원)으로 표시
for i in contour2 :
    for j in i :
        cv2.circle(img2, tuple(j[0]), 1, (255, 0, 0), -1)    
    
cv2.imshow('CHAIN_APPROX_NONE', img)
cv2.imshow('CHAIN_APPROX_SIMPLE', img2)
cv2.waitKey()
cv2.destroyAllWindows()

[array([[[338,  19]],

       [[337,  20]],

       [[336,  20]],

       [[335,  20]],

       [[334,  20]],

       [[333,  20]],

       [[332,  21]],

       [[331,  21]],

       [[330,  21]],

       [[329,  21]],

       [[328,  22]],

       [[327,  22]],

       [[326,  22]],

       [[325,  23]],

       [[324,  23]],

       [[323,  23]],

       [[322,  24]],

       [[321,  24]],

       [[320,  25]],

       [[319,  25]],

       [[318,  26]],

       [[317,  26]],

       [[316,  27]],

       [[315,  28]],

       [[314,  28]],

       [[313,  29]],

       [[312,  30]],

       [[311,  30]],

       [[310,  31]],

       [[309,  32]],

       [[308,  33]],

       [[307,  34]],

       [[306,  35]],

       [[305,  36]],

       [[304,  37]],

       [[303,  38]],

       [[302,  39]],

       [[301,  40]],

       [[300,  41]],

       [[300,  42]],

       [[299,  43]],

       [[298,  44]],

       [[298,  45]],

       [[297,  46]],

       [[296,  47]],

       [[

In [36]:
# 컨투어 계층 트리

import cv2
import numpy as np

# 영상 읽기
img = cv2.imread('./img/shapes_donut.png')
img2 = img.copy()

# 바이너리 이미지로 변환
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, imthres = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)

# 가장 바깥 컨투어만 수집
im2, contour, hierarchy = cv2.findContours(imthres, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
print(len(contour))
print(hierarchy)

# 가장 바깥 컨투어만 그리기
cv2.drawContours(img, contour, -1, (0, 255, 0), 3)

# 모든 컨투어를 트리 계층으로 수집
im2, contour2, hierarchy = cv2.findContours(imthres, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE) # cv2.CHAIN_APPROX_SIMPLE)
print(len(contour2))
print(hierarchy)

# 가장 바깥 컨투어만 그리기
cv2.drawContours(img, contour, -1, (0, 255, 0), 3)

# cv2.drawContours(img2, contour2, -1, (0, 255, 0), 3)

# 모든 컨투어 그리기
for idx, cont in enumerate(contour2) :
    # 랜덤한 컬러 추출
    color = [int(i) for i in np.random.randint(0, 255, 3)]
    # 컨투어 인덱스마다 랜덤한 색상으로 그리기
    cv2.drawContours(img2, contour2, idx, color, 3)
    # 컨투어 첫 좌표에 인덱스 숫자 표시
    cv2.putText(img2, str(idx), tuple(cont[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))

cv2.imshow('RETR_EXTERNAL', img)
cv2.imshow('CHAIN_APPROX_SIMPLE', img2)
cv2.waitKey()
cv2.destroyAllWindows()

3
[[[ 1 -1 -1 -1]
  [ 2  0 -1 -1]
  [-1  1 -1 -1]]]
6
[[[ 2 -1  1 -1]
  [-1 -1 -1  0]
  [ 4  0  3 -1]
  [-1 -1 -1  2]
  [-1  2  5 -1]
  [-1 -1 -1  4]]]


In [40]:
# 모멘트를 이용한 중심점, 넓이, 둘레길이

import cv2
import numpy as np

img = cv2.imread('./img/shapes.png')
# cv2.imshow('img', img)
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# cv2.imshow('imgray', imgray)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
img2, contours, hierarchy = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# 각 도형의 컨투어에 대한 루프
for c in contours :
    # 모멘트 계산
    mmt = cv2.moments(c)
    # print(mmt)
    # m10/m00, m01/m00 중심점 계산
    cx = int(mmt['m10'] / mmt['m00'])
    cy = int(mmt['m01'] / mmt['m00'])
    # 영역 넓이
    a = mmt['m00']
    print(a)
    # 영역 외곽선 그리기
    l = cv2.arcLength(c, True)
    print(l)
    # 중심점에 노란색 점 그리기
    cv2.circle(img, (cx, cy), 5, (0, 255, 255), -1)
    
cv2.imshow('center', img)
cv2.waitKey()
cv2.destroyAllWindows()

9870.0
370.6761865615845
12544.0
448.0
6216.0
382.3919162750244


In [31]:
# 컨투어를 감싸는 도형 그리기

import cv2
import numpy as np

img = cv2.imread('./traffic_sign.png')
# cv2.imshow('img', img)
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('imgray', imgray)
imgray = cv2.GaussianBlur(imgray, (3, 3), 0)
# cv2.imshow('blur', blur)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
# cv2.imshow('th', th)

# 컨투어 찾기
im, contours, hr = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
# print(contours[0])
cv2.drawContours(img, contours, -1, (0, 255, 0), 3)
contr = contours[0]

# 감싸는 사각형 표시(검은색)
x, y, w, h = cv2.boundingRect(contr)
print(x, y, w, h)
# (x, y) : 사각형 왼쪽 상단 좌표
cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 0), 3)

cv2.imshow('center', img)
cv2.waitKey()
cv2.destroyAllWindows()

17 17 109 94


In [ ]:
# (x, y) 좌표가 (73, 114)
# 폭과 높이가 1, 1로 나온다?!
# -> 블러 처리

In [44]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg')
# cv2.imshow('img', img)
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('imgray', imgray)
imgray = cv2.GaussianBlur(imgray, (3, 3), 0)
# cv2.imshow('blur', blur)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
# cv2.imshow('th', th)

# 컨투어 찾기
im, contours, hr = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
# print(contours[0])
print(len(contours))
cv2.drawContours(img, contours, -1, (0, 255, 0), 3)
contr = contours[0]

# 감싸는 사각형 표시(검은색)
x, y, w, h = cv2.boundingRect(contr)
print(x, y, w, h)
# (x, y) : 사각형 왼쪽 상단 좌표
cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 0), 3)

cv2.imshow('center', img)
cv2.waitKey()
cv2.destroyAllWindows()

27
140 300 10 2


In [53]:
import cv2
import numpy as np

img = cv2.imread('./coin_spread.jpg')
# cv2.imshow('img', img)
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('imgray', imgray)
imgray = cv2.GaussianBlur(imgray, (3, 3), 0)
# cv2.imshow('blur', blur)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
# cv2.imshow('th', th)

# 컨투어 찾기
im, contours, hr = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
# print(contours[0])
print(len(contours))
cv2.drawContours(img, contours, -1, (0, 255, 0), 3)
contr = contours[0]

# 감싸는 사각형 표시(검은색)
x, y, w, h = cv2.boundingRect(contr)
print(x, y, w, h)
# (x, y) : 사각형 왼쪽 상단 좌표
cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 0), 3)

cv2.imshow('center', img)
cv2.waitKey()
cv2.destroyAllWindows()

28
477 405 1 1


In [30]:
# 근사 컨투어

import cv2
import numpy as np

img = cv2.imread('./img/bad_rect.png')
img2 = img.copy()
# cv2.imshow('img2', img2)

imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY)
# cv2.imshow('th', th)

temp, contours, hierarchy = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contour = contours[0]

# 전체 둘레의 0.05로 오차범위 지정
epsilon = 0.05 * cv2.arcLength(contour, True)
# 근사 컨투어 계산
approx = cv2.approxPolyDP(contour, epsilon, True)

# 각각 컨투어 선 그리기
cv2.drawContours(img, [contour], -1, (0, 255, 0), 3)
cv2.drawContours(img2, [approx], -1, (0, 255, 0), 3)

cv2.imshow('contour', img)
cv2.imshow('approx', img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [54]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg')
img2 = img.copy()
# cv2.imshow('img2', img2)

imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
imgray = cv2.GaussianBlur(imgray, (3, 3), 0)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
# cv2.imshow('th', th)

temp, contours, hierarchy = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contour = contours[0]

# 전체 둘레의 0.05로 오차범위 지정
epsilon = 0.05 * cv2.arcLength(contour, True)
# 근사 컨투어 계산
approx = cv2.approxPolyDP(contour, epsilon, True)

# 각각 컨투어 선 그리기
cv2.drawContours(img, [contour], -1, (0, 255, 0), 3)
cv2.drawContours(img2, [approx], -1, (0, 255, 0), 3)

cv2.imshow('contour', img)
cv2.imshow('approx', img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [57]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg')
img2 = img.copy()
# cv2.imshow('img2', img2)

imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
imgray = cv2.GaussianBlur(imgray, (3, 3), 0)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
# cv2.imshow('th', th)

temp, contours, hierarchy = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contour = contours[0]

# 전체 둘레의 0.05로 오차범위 지정
epsilon = 0.05 * cv2.arcLength(contour, True)
# 근사 컨투어 계산
approx = cv2.approxPolyDP(contour, epsilon, True)

# 각각 컨투어 선 그리기
cv2.drawContours(img, [contour], -1, (0, 255, 0), 3)
cv2.drawContours(img2, [approx], -1, (0, 255, 0), 3)

cv2.imshow('contour', img)
cv2.imshow('approx', img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [58]:
# 왜 안 되는가??!!!!!!

import cv2
import numpy as np

img = cv2.imread('./coin_spread.jpg')
img2 = img.copy()
# cv2.imshow('img2', img2)

imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
imgray = cv2.GaussianBlur(imgray, (3, 3), 0)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
# cv2.imshow('th', th)

temp, contours, hierarchy = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print(contours)
contour = contours[0]

# 전체 둘레의 0.05로 오차범위 지정
epsilon = 0.05 * cv2.arcLength(contour, True)
# 근사 컨투어 계산
approx = cv2.approxPolyDP(contour, epsilon, True)

# 각각 컨투어 선 그리기
cv2.drawContours(img, [contour], -1, (0, 255, 0), 3)
cv2.drawContours(img2, [approx], -1, (0, 255, 0), 3)

cv2.imshow('contour', img)
cv2.imshow('approx', img2)
cv2.waitKey()
cv2.destroyAllWindows()

[array([[[477, 405]]], dtype=int32), array([[[479, 402]]], dtype=int32), array([[[574, 354]],

       [[573, 355]],

       [[566, 355]],

       [[565, 356]],

       [[561, 356]],

       [[560, 357]],

       [[556, 357]],

       [[555, 358]],

       [[553, 358]],

       [[552, 359]],

       [[550, 359]],

       [[549, 360]],

       [[547, 360]],

       [[546, 361]],

       [[544, 361]],

       [[543, 362]],

       [[541, 362]],

       [[540, 363]],

       [[538, 363]],

       [[537, 364]],

       [[536, 364]],

       [[535, 365]],

       [[534, 365]],

       [[533, 366]],

       [[532, 366]],

       [[531, 367]],

       [[529, 367]],

       [[528, 368]],

       [[527, 368]],

       [[526, 369]],

       [[525, 369]],

       [[523, 371]],

       [[522, 371]],

       [[521, 372]],

       [[520, 372]],

       [[519, 373]],

       [[518, 373]],

       [[516, 375]],

       [[515, 375]],

       [[514, 376]],

       [[513, 376]],

       [[511, 378]],

   

In [35]:
# 도형 매칭으로 비슷한 도형 찾기

import cv2
import numpy as np

# 매칭을 위한 이미지 읽기
target = cv2.imread('./img/4star.jpg')  # 매칭 대상
shapes = cv2.imread('./img/shapestomatch.jpg')  # 여러 도형

targetGray = cv2.cvtColor(target, cv2.COLOR_BGR2GRAY)
shapesGray = cv2.cvtColor(shapes, cv2.COLOR_BGR2GRAY)

ret, targetTh = cv2.threshold(targetGray, 127, 255, cv2.THRESH_BINARY_INV)
ret, shapesTh = cv2.threshold(shapesGray, 127, 255, cv2.THRESH_BINARY_INV)

_, cntrs_target, _ = cv2.findContours(targetTh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
# print(len(cntrs_target))
_, cntrs_shapes, _ = cv2.findContours(shapesTh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
# print(len(cntrs_shapes))

# 각 도형과 매칭을 위한 반복문
matchs = []  # 컨투어와 매칭 점수를 보관할 리스트
for contr in cntrs_shapes :
    # 대상 도형과 여러 도형 중 하나와 매칭 실행              
    match = cv2.matchShapes(cntrs_target[0], contr, cv2.CONTOURS_MATCH_I2, 0.0)
    # 해당 도형의 매칭 점수와 컨투어를 쌍으로 저장
    matchs.append( (match, contr) )
    # 해당 도형의 컨투어 시작 지점에 매칭 점수 표시
    cv2.putText(shapes, '%.2f'%match, tuple(contr[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255), 1)

matchs.sort(key = lambda x : x[0])
# print(matchs)

# 가장 적은 매칭 점수를 얻는 도형의 컨투어에 선 그리기
cv2.drawContours(shapes, [matchs[0][1]], -1, (0, 255, 0), 3)

cv2.imshow('target', target)
cv2.imshow('Match Shape', shapes)
cv2.waitKey()
cv2.destroyAllWindows()

In [45]:
import cv2
import numpy as np

# 매칭을 위한 이미지 읽기
target = cv2.imread('./traffic_sign4.png') # 매칭 대상
shapes = cv2.imread('./traffic_sign3.jpeg')  # 여러 도형

targetGray = cv2.cvtColor(target, cv2.COLOR_BGR2GRAY)
targetGray = cv2.GaussianBlur(targetGray, (3, 3), 0)

shapesGray = cv2.cvtColor(shapes, cv2.COLOR_BGR2GRAY)
shapesGray = cv2.GaussianBlur(shapesGray, (3, 3), 0)

ret, targetTh = cv2.threshold(targetGray, 127, 255, cv2.THRESH_BINARY_INV)
ret, shapesTh = cv2.threshold(shapesGray, 127, 255, cv2.THRESH_BINARY_INV)

_, cntrs_target, _ = cv2.findContours(targetTh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
# print(len(cntrs_target))
_, cntrs_shapes, _ = cv2.findContours(shapesTh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
# print(len(cntrs_shapes))

# 각 도형과 매칭을 위한 반복문
matchs = []  # 컨투어와 매칭 점수를 보관할 리스트
for contr in cntrs_shapes :
    # 대상 도형과 여러 도형 중 하나와 매칭 실행              
    match = cv2.matchShapes(cntrs_target[0], contr, cv2.CONTOURS_MATCH_I2, 0.0)
    # 해당 도형의 매칭 점수와 컨투어를 쌍으로 저장
    matchs.append( (match, contr) )
    # 해당 도형의 컨투어 시작 지점에 매칭 점수 표시
    cv2.putText(shapes, '%.2f'%match, tuple(contr[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255), 1)

matchs.sort(key = lambda x : x[0])
# print(matchs)

# 가장 적은 매칭 점수를 얻는 도형의 컨투어에 선 그리기
cv2.drawContours(shapes, [matchs[0][1]], -1, (0, 255, 0), 3)

cv2.imshow('target', target)
cv2.imshow('Match Shape', shapes)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
import cv2
import numpy as np

# 매칭을 위한 이미지 읽기
target = cv2.imread('./traffic_sign4.png') # 매칭 대상
shapes = cv2.imread('./traffic_sign3.jpeg')  # 여러 도형

targetGray = cv2.cvtColor(target, cv2.COLOR_BGR2GRAY)
targetGray = cv2.GaussianBlur(targetGray, (3, 3), 0)

shapesGray = cv2.cvtColor(shapes, cv2.COLOR_BGR2GRAY)
shapesGray = cv2.GaussianBlur(shapesGray, (3, 3), 0)

ret, targetTh = cv2.threshold(targetGray, 127, 255, cv2.THRESH_BINARY_INV)
ret, shapesTh = cv2.threshold(shapesGray, 127, 255, cv2.THRESH_BINARY_INV)

_, cntrs_target, _ = cv2.findContours(targetTh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print(len(cntrs_target))
_, cntrs_shapes, _ = cv2.findContours(shapesTh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print(len(cntrs_shapes))

# 모든 컨투어 그리기
for idx, cont in enumerate(cntrs_shapes) :
    # 랜덤한 컬러 추출
    color = [int(i) for i in np.random.randint(0, 255, 3)]
    # 컨투어 인덱스마다 랜덤한 색상으로 그리기
    cv2.drawContours(shapes, cntrs_shapes, idx, color, 3)
    # 컨투어 첫 좌표에 인덱스 숫자 표시
    # cv2.putText(img2, str(idx), tuple(cont[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))

# # 각 도형과 매칭을 위한 반복문
# matchs = []  # 컨투어와 매칭 점수를 보관할 리스트
# for contr in cntrs_shapes :
#     # 대상 도형과 여러 도형 중 하나와 매칭 실행              
#     match = cv2.matchShapes(cntrs_target[0], contr, cv2.CONTOURS_MATCH_I2, 0.0)
#     # 해당 도형의 매칭 점수와 컨투어를 쌍으로 저장
#     matchs.append( (match, contr) )
#     # 해당 도형의 컨투어 시작 지점에 매칭 점수 표시
#     cv2.putText(shapes, '%.2f'%match, tuple(contr[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255), 1)

# matchs.sort(key = lambda x : x[0])
# # print(matchs)

# # 가장 적은 매칭 점수를 얻는 도형의 컨투어에 선 그리기
# cv2.drawContours(shapes, [matchs[0][1]], -1, (0, 255, 0), 3)

cv2.imshow('target', target)
cv2.imshow('Match Shape', shapes)
cv2.waitKey()
cv2.destroyAllWindows()

1
27


In [13]:
import cv2
import numpy as np

# 매칭을 위한 이미지 읽기
target = cv2.imread('./traffic_sign4.png') # 매칭 대상
shapes = cv2.imread('./traffic_sign3.jpeg')  # 여러 도형

target = cv2.pyrMeanShiftFiltering(target, 20, 50)
cv2.imshow('target', target)
targetGray = cv2.cvtColor(target, cv2.COLOR_BGR2GRAY)

shapes = cv2.pyrMeanShiftFiltering(shapes, 20, 50)
cv2.imshow('shapes', shapes)
shapesGray = cv2.cvtColor(shapes, cv2.COLOR_BGR2GRAY)

ret, targetTh = cv2.threshold(targetGray, 127, 255, cv2.THRESH_BINARY_INV)
ret, shapesTh = cv2.threshold(shapesGray, 127, 255, cv2.THRESH_BINARY_INV)

_, cntrs_target, _ = cv2.findContours(targetTh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print(len(cntrs_target))
_, cntrs_shapes, _ = cv2.findContours(shapesTh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print(len(cntrs_shapes))

# 모든 컨투어 그리기
for idx, cont in enumerate(cntrs_shapes) :
    # 랜덤한 컬러 추출
    color = [int(i) for i in np.random.randint(0, 255, 3)]
    # 컨투어 인덱스마다 랜덤한 색상으로 그리기
    cv2.drawContours(shapes, cntrs_shapes, idx, color, 3)
    # 컨투어 첫 좌표에 인덱스 숫자 표시
    # cv2.putText(img2, str(idx), tuple(cont[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255))

# # 각 도형과 매칭을 위한 반복문
# matchs = []  # 컨투어와 매칭 점수를 보관할 리스트
# for contr in cntrs_shapes :
#     # 대상 도형과 여러 도형 중 하나와 매칭 실행              
#     match = cv2.matchShapes(cntrs_target[0], contr, cv2.CONTOURS_MATCH_I2, 0.0)
#     # 해당 도형의 매칭 점수와 컨투어를 쌍으로 저장
#     matchs.append( (match, contr) )
#     # 해당 도형의 컨투어 시작 지점에 매칭 점수 표시
#     cv2.putText(shapes, '%.2f'%match, tuple(contr[0][0]), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 255), 1)

# matchs.sort(key = lambda x : x[0])
# # print(matchs)

# # 가장 적은 매칭 점수를 얻는 도형의 컨투어에 선 그리기
# cv2.drawContours(shapes, [matchs[0][1]], -1, (0, 255, 0), 3)

# cv2.imshow('target', target)
# cv2.imshow('Match Shape', shapes)
cv2.waitKey()
cv2.destroyAllWindows()

13
43


In [70]:
# 허프 원 검출

import cv2
import numpy as np

img = cv2.imread('./coin_spread.jpg')
cv2.imshow('img', img)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow('gray', gray)
blur = cv2.GaussianBlur(gray, (3, 3), 0)
cv2.imshow('blur', blur)

# 허프 원 변환 적용(dp = 1.5, minDist = 30, cany_max = 200)
circles = cv2.HoughCircles(blur, cv2.HOUGH_GRADIENT, 1.5, 30, None, 320)
if circles is not None :
    circles = np.uint16(np.around(circles))
    for i in circles[0, :] :
        # 원 둘레에 초록색 원 그리기
        cv2.circle(img, (i[0], i[1]), i[2], (0, 255, 0), 2)
        # 원 중심점에 빨간색 원 그리기
        cv2.circle(img, (i[0], i[1]), 2, (0, 0, 255), 5)

# 결과 출력
cv2.imshow('hough circle', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [71]:
# 연결된 영역 레이블링

import cv2
import numpy as np

img = cv2.imread('./img/shapes_donut.png')
img2 = np.zeros_like(img)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, th = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)

cnt, labels = cv2.connectedComponents(th)
# retval, labels, stats, cent = cv2.connectedComponentsWithStats(th)

# 레이블 개수만큼 순회
for i in range(cnt) :
    # 레이블이 같은 영역에 랜덤한 색상 적용
    img2[labels == i] = [int(j) for j in np.random.randint(0, 255, 3)]
    
# 결과 출력
cv2.imshow('origin', img)
cv2.imshow('labeled', img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [79]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg')
img2 = np.zeros_like(img)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray = cv2.GaussianBlur(gray, (3, 3), 0)
_, th = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)

# cnt, labels = cv2.connectedComponents(th)
# print(cnt)
retval, labels, stats, cent = cv2.connectedComponentsWithStats(th)

# 레이블 개수만큼 순회
for i in range(cnt) :
    # 레이블이 같은 영역에 랜덤한 색상 적용
    img2[labels == i] = [int(j) for j in np.random.randint(0, 255, 3)]
    
# 결과 출력
cv2.imshow('origin', img)
cv2.imshow('labeled', img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [83]:
# 마우스와 그랩컷으로 배경 분리

import cv2
import numpy as np

img = cv2.imread('./img/taekwonv1.jpg')
img_draw = img.copy()
mask = np.zeros(img.shape[:2], dtype=np.uint8)  # 마스크 생성
rect = [0,0,0,0]    # 사각형 영역 좌표 초기화
mode = cv2.GC_EVAL  # 그랩컷 초기 모드
# 배경 및 전경 모델 버퍼
bgdmodel = np.zeros((1,65),np.float64)
fgdmodel = np.zeros((1,65),np.float64)

# 마우스 이벤트 처리 함수
def onMouse(event, x, y, flags, param):
    global mouse_mode, rect, mask, mode
    if event == cv2.EVENT_LBUTTONDOWN : # 왼쪽 마우스 누름
        if flags <= 1: # 아무 키도 안 눌렀으면
            mode = cv2.GC_INIT_WITH_RECT # 드래그 시작, 사각형 모드 ---①
            rect[:2] = x, y # 시작 좌표 저장
    # 마우스가 움직이고 왼쪽 버튼이 눌러진 상태
    elif event == cv2.EVENT_MOUSEMOVE and flags & cv2.EVENT_FLAG_LBUTTON :
        if mode == cv2.GC_INIT_WITH_RECT: # 드래그 진행 중 ---②
            img_temp = img.copy()
            # 드래그 사각형 화면에 표시
            cv2.rectangle(img_temp, (rect[0], rect[1]), (x, y), (0,255,0), 2)
            cv2.imshow('img', img_temp)
        elif flags > 1: # 키가 눌러진 상태
            mode = cv2.GC_INIT_WITH_MASK    # 마스크 모드 ---③
            if flags & cv2.EVENT_FLAG_CTRLKEY :# 컨트롤 키, 분명한 전경
                # 흰색 점 화면에 표시
                cv2.circle(img_draw,(x,y),3, (255,255,255),-1)
                # 마스크에 GC_FGD로 채우기      ---④
                cv2.circle(mask,(x,y),3, cv2.GC_FGD,-1)
            if flags & cv2.EVENT_FLAG_SHIFTKEY : # 쉬프트키, 분명한 배경
                # 검정색 점 화면에 표시
                cv2.circle(img_draw,(x,y),3, (0,0,0),-1)
                # 마스크에 GC_BGD로 채우기      ---⑤
                cv2.circle(mask,(x,y),3, cv2.GC_BGD,-1)
            cv2.imshow('img', img_draw) # 그려진 모습 화면에 출력
    elif event == cv2.EVENT_LBUTTONUP: # 마우스 왼쪽 버튼 뗀 상태 ---⑥
        if mode == cv2.GC_INIT_WITH_RECT : # 사각형 그리기 종료
            rect[2:] =x, y # 사각형 마지막 좌표 수집
            # 사각형 그려서 화면에 출력 ---⑦
            cv2.rectangle(img_draw, (rect[0], rect[1]), (x, y), (255,0,0), 2)
            cv2.imshow('img', img_draw)
        # 그랩컷 적용 ---⑧
        cv2.grabCut(img, mask, tuple(rect), bgdmodel, fgdmodel, 1, mode)
        img2 = img.copy()
        # 마스크에 확실한 배경, 아마도 배경으로 표시된 영역을 0으로 채우기
        img2[(mask==cv2.GC_BGD) | (mask==cv2.GC_PR_BGD)] = 0
        cv2.imshow('grabcut', img2) # 최종 결과 출력
        mode = cv2.GC_EVAL # 그랩컷 모드 리셋
# 초기 화면 출력 및 마우스 이벤트 등록
cv2.imshow('img', img)
cv2.setMouseCallback('img', onMouse)
while True:    
    if cv2.waitKey(0) & 0xFF == 27 : # esc
        break
cv2.destroyAllWindows()

In [3]:
# 도형 알아맞히기

import cv2
import numpy as np

img = cv2.imread('./traffic_sign.png')
cv2.imshow('img', img)
img2 = img.copy()
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
imgray = cv2.GaussianBlur(imgray, (3, 3), 0)
# cv2.imshow('imgray', imgray)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
# cv2.imshow('th', th)

_, contours, _ = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
# print(len(contours))  # 5

for contour in contours : 
    # 각 컨투어에 근사 컨투어로 단순화
    approx = cv2.approxPolyDP(contour, 0.01*cv2.arcLength(contour, True), True)
    print(approx)
    # 꼭짓점의 개수
    vertices = len(approx)
    print('vertices : ', vertices)
    
    # 중심점 찾기
    mmt = cv2.moments(contour)
    cx, cy = int(mmt['m10']/mmt['m00']), int(mmt['m01']/mmt['m00'])

for i in approx :
    for j in i :
        # print(tuple(j))
        cv2.circle(img, tuple(j), 1, (255, 0, 0), -1)

cv2.imshow('Input Shapes', img)
# cv2.imshow('Recognizing Shapes', img2)
cv2.waitKey()
cv2.destroyAllWindows()

[[[ 19  17]]

 [[ 33  48]]

 [[ 73 110]]

 [[125  18]]]
vertices :  4


In [ ]:
# 도형 알아맞히기

import cv2
import numpy as np

img = cv2.imread('./img/5shapes.jpg')
# cv2.imshow('img', img)
img2 = img.copy()
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# cv2.imshow('imgray', imgray)
ret, th = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY_INV)
# cv2.imshow('th', th)

_, contours, _ = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
# print(len(contours))  # 5

for contour in contours : 
    # 각 컨투어에 근사 컨투어로 단순화
    approx = cv2.approxPolyDP(contour, 0.01*cv2.arcLength(contour, True), True)
    # 꼭짓점의 개수
    vertices = len(approx)
    print('vertices : ', vertices)
    
    # 중심점 찾기
    mmt = cv2.moments(contour)
    cx, cy = int(mmt['m10']/mmt['m00']), int(mmt['m01']/mmt['m00'])

# cv2.imshow('Input Shapes', img)
# cv2.imshow('Recognizing Shapes', img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [32]:
# 거리 변환으로 전신 스켈레톤 찾기

import cv2
import numpy as np

img = cv2.imread('./img/full_body.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imshow('img', img)
_, biimg = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV)
cv2.imshow('biimg', biimg)

# 거리 변환
dst = cv2.distanceTransform(biimg, cv2.DIST_L2, 5)
# 거리 값을 0 ~ 255 범위로 정규화
dst = (dst / (dst.max() - dst.min()) * 255).astype(np.uint8)
# 거리 값에 스레시홀드로 완전한 뼈대 찾기
skeleton = cv2.adaptiveThreshold(dst, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 7, -3)

# 결과 출력
# cv2.imshow('origin', img)
cv2.imshow('dst', dst)
cv2.imshow('skeleton', skeleton)
cv2.waitKey()
cv2.destroyAllWindows()

In [33]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg', cv2.IMREAD_GRAYSCALE)
cv2.imshow('img', img)
_, biimg = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV)
cv2.imshow('biimg', biimg)

# 거리 변환
dst = cv2.distanceTransform(biimg, cv2.DIST_L2, 5)
# 거리 값을 0 ~ 255 범위로 정규화
dst = (dst / (dst.max() - dst.min()) * 255).astype(np.uint8)
# 거리 값에 스레시홀드로 완전한 뼈대 찾기
skeleton = cv2.adaptiveThreshold(dst, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 7, -3)

# 결과 출력
# cv2.imshow('origin', img)
cv2.imshow('dst', dst)
cv2.imshow('skeleton', skeleton)
cv2.waitKey()
cv2.destroyAllWindows()

In [13]:
# 동전 개수 세기

import cv2
import numpy as np

img = cv2.imread('./img/coins_connected.jpg')
print(img.shape) # (419, 601, 3)
rows, cols = img.shape[:2]
cv2.imshow('original', img)

# 동전 표면을 흐릿하게 피라미드 평균 시프트 적용
mean = cv2.pyrMeanShiftFiltering(img, 20, 50)
cv2.imshow('mean', mean)

# 바이너리 이미지 변환
gray = cv2.cvtColor(mean, cv2.COLOR_BGR2GRAY)
# cv2.imshow('gray1', gray)
gray = cv2.GaussianBlur(gray, (3, 3), 0)
# cv2.imshow('gray2', gray)

_, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
# cv2.imshow('thresh', thresh)

# 거리 변환
dst = cv2.distanceTransform(thresh, cv2.DIST_L2, 3)
print(len(dst)) # 419
# 거리 값을 0 ~ 255로 변환
dst = (dst / (dst.max() - dst.min()) * 255).astype(np.uint8)
cv2.imshow('dst', dst)
# skeleton = cv2.adaptiveThreshold(dst, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 7, -3)
# cv2.imshow('skeleton', skeleton)

# 거리 변환 결과에서 로컬 최대값 구하기
## 팽창 적용(동전 크기 정도의 구조화 요소 필요)
localMx = cv2.dilate(dst, np.ones((50, 50), np.uint8))
cv2.imshow('localMx1', localMx)
## 로컬 최대 값을 저장할 배열 생성
lm = np.zeros((rows, cols), np.uint8)
## 팽창 적용 전 이미지와 같은 픽셀이 로컬 최대 값이므로 255로 설정
lm[(localMx==dst) & (dst != 0)] = 255
cv2.imshow('localMx2', lm)

# 로컬 최대 값으로 색 채우기
## 로컬 최대 값이 있는 좌표 구하기
seeds = np.where(lm == 255)
print(seeds[1], len(seeds[1]))
print(seeds[0], len(seeds[0])) 

seed = np.stack((seeds[1], seeds[0]), axis = -1)
print(seed)

# 색 채우기를 위한 채우기 마스크 생성
fill_mask = np.zeros( (rows+2, cols+2), np.uint8 )
for x, y in seed :
    ## 로컬 최대 값을 시드로 해서 평균 시프트 영상에 색 채우기
    ret = cv2.floodFill(mean, fill_mask, (x, y), (255, 255, 255), (10, 10, 10), (10, 10, 10))
cv2.imshow('floodFill', mean)

# 색 채우기를 적용한 영상에 다시 거리 변환 적용
gray = cv2.cvtColor(mean, cv2.COLOR_BGR2GRAY)
# cv2.imshow('gray3', gray)
gray = cv2.GaussianBlur(gray, (5, 5), 0)
# cv2.imshow('gray4', gray)

ret, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
dst = cv2.distanceTransform(thresh, cv2.DIST_L2, 5)
dst = (dst / (dst.max() - dst.min()) * 255).astype(np.uint8)
cv2.imshow('dst2', dst)

# 거리 변환 결과 값의 절반 이상을 차지한 영역은 확실한 전경으로 설정
ret, sure_fg = cv2.threshold(dst, 0.5*dst.max(), 255, 0)
cv2.imshow('sure_fg', sure_fg)

# 거리 변환 결과를 반전해서 확실한 배경 찾기
_, bg_th = cv2.threshold(dst, 0.3*dst.max(), 255, cv2.THRESH_BINARY_INV)
bg_dst = cv2.distanceTransform(bg_th, cv2.DIST_L2, 5)
bg_dst = (bg_dst / (bg_dst.max() - bg_dst.min()) * 255).astype(np.uint8)
ret, sure_bg = cv2.threshold(bg_dst, 0.3*bg_dst.max(), 255, cv2.THRESH_BINARY)
cv2.imshow('sure_bg', sure_bg)

# 불확실한 영역 설정 : 확실한 배경을 반전해서 확실한 전경을 빼기
ret, inv_sure_bg = cv2.threshold(sure_bg, 127, 255, cv2.THRESH_BINARY_INV)
unknown = cv2.subtract(inv_sure_bg, sure_fg)
cv2.imshow('unknown', unknown)

# 연결된 요소 레이블링
_, markers = cv2.connectedComponents(sure_fg)

# 레이블링을 1씩 증가시키고 레이블을 알 수 없는 영역을 0번 레이블로 설정
markers = markers + 1
markers[unknown == 255] = 0
print('워터셰드 전 : ', np.unique(markers))
colors = []
marker_show = np.zeros_like(img)
# 선택한 마커 아이디 개수만큼 반복
for mid in np.unique(markers) :
    color = [int(j) for j in np.random.randint(0, 255, 3)]
    colors.append((mid, color))
    marker_show[markers==mid] = color
##############################################################################################################    

cv2.waitKey()
cv2.destroyAllWindows()

(419, 601, 3)
419
[425 426 427 425 426 427 428 208 209 208 209 208 209 318 518 518 519 519
  91  92  92 421 422 423 424 425 423 424 425 209 210 209 210 316 316 532
 532 533 532 533 532 533  90  91  89  90 399 399 400 400 311 188 187 188
 187 188 187 188 187 188 461 460 461 459 460 459 458] 67
[ 75  75  75  76  76  76  76  92  92  93  93  94  94 121 129 130 130 131
 140 140 141 199 199 199 199 199 200 200 200 215 215 216 216 219 220 247
 248 248 249 249 250 250 265 265 266 266 312 313 314 315 328 335 336 336
 337 337 338 338 339 339 351 352 352 353 353 354 355] 67
[[425  75]
 [426  75]
 [427  75]
 [425  76]
 [426  76]
 [427  76]
 [428  76]
 [208  92]
 [209  92]
 [208  93]
 [209  93]
 [208  94]
 [209  94]
 [318 121]
 [518 129]
 [518 130]
 [519 130]
 [519 131]
 [ 91 140]
 [ 92 140]
 [ 92 141]
 [421 199]
 [422 199]
 [423 199]
 [424 199]
 [425 199]
 [423 200]
 [424 200]
 [425 200]
 [209 215]
 [210 215]
 [209 216]
 [210 216]
 [316 219]
 [316 220]
 [532 247]
 [532 248]
 [533 248]
 [532 249]
 

In [15]:
import cv2
import numpy as np

# 이미지 읽기
img = cv2.imread('./img/coins_connected.jpg')
rows, cols = img.shape[:2]
cv2.imshow('original', img)


# 동전 표면을 흐릿하게 피라미드평균시프트 적용
mean = cv2.pyrMeanShiftFiltering(img, 20, 50)
cv2.imshow('mean', mean)
# 바이너리 이미지 변환
gray = cv2.cvtColor(mean, cv2.COLOR_BGR2GRAY)
gray = cv2.GaussianBlur(gray, (3,3), 0)

_, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
cv2.imshow('thresh', thresh)
# 거리 변환
dst = cv2.distanceTransform(thresh, cv2.DIST_L2, 3)
# 거리 값을 0 ~255로 변환
dst = ( dst / (dst.max() - dst.min()) * 255 ).astype(np.uint8)
cv2.imshow('dst', dst)

# 거리 변환결과에서 로칼 최대 값 구하기
## 팽창 적용(동전 크기 정도의 구조화 요소 필요),
localMx = cv2.dilate(dst, np.ones((50,50), np.uint8))
## 로칼 최대 값 저장 할 배열 생성
lm = np.zeros((rows, cols), np.uint8)
## 팽창 적용전 이미지와 같은 픽셀이 로컬 최대 값이므로 255로 설정
lm[(localMx==dst) & (dst != 0)] = 255
cv2.imshow('localMx', lm)

# 로컬 최대값으로 색 채우기
## 로컬 최대 값이 있는 좌표 구하기
seeds = np.where(lm ==255)
seed = np.stack( (seeds[1], seeds[0]), axis=-1)
## 색 채우기를 위한 채우기 마스크 생성
fill_mask = np.zeros((rows+2, cols+2), np.uint8)
for x,y in seed:
    ## 로칼 최대값을 시드로해서 평균 시프트 영상에 색채우기 
    ret = cv2.floodFill(mean, fill_mask, (x,y), (255,255,255), \
                                            (10,10,10), (10,10,10))
cv2.imshow('floodFill', mean)

# 색 채우기 적용한 영상에 다시 거리 변환 적용
gray = cv2.cvtColor(mean, cv2.COLOR_BGR2GRAY)
gray = cv2.GaussianBlur(gray, (5,5), 0)

ret, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
dst = cv2.distanceTransform(thresh, cv2.DIST_L2, 5)
dst = ( (dst / (dst.max() - dst.min())) * 255 ).astype(np.uint8)
cv2.imshow('dst2', dst)

# 거리 변환 결과값의 절반 이상을 차지한 영역은 확실한 전경으로 설정
ret, sure_fg = cv2.threshold(dst, 0.5*dst.max(), 255,0)
cv2.imshow('sure_fg', sure_fg)

# 거리 변환 결과를 반전해서 확실한 배경 찾기
_, bg_th = cv2.threshold(dst, 0.3*dst.max(),  255, cv2.THRESH_BINARY_INV)
bg_dst = cv2.distanceTransform(bg_th, cv2.DIST_L2, 5)
bg_dst = ( (bg_dst / (bg_dst.max() - bg_dst.min())) * 255 ).astype(np.uint8)
ret, sure_bg = cv2.threshold(bg_dst, 0.3*bg_dst.max(), 255,cv2.THRESH_BINARY)
cv2.imshow('sure_bg', sure_bg)


# 불확실한 영역 설정 : 확실한 배경을 반전해서 확실한 전경을 빼기
ret, inv_sure_bg = cv2.threshold(sure_bg, 127, 255,cv2.THRESH_BINARY_INV)
unkown = cv2.subtract(inv_sure_bg, sure_fg)
cv2.imshow('unkown', unkown)

# 연결된 요소 레이블링
_, markers = cv2.connectedComponents(sure_fg)

# 레이블링을 1씩 증가 시키고 0번 레이블 알 수 없는 영역을 0번 레이블로 설정
markers = markers+1
markers[unkown ==255] = 0
print("워터쉐드 전:", np.unique(markers))
colors = []
marker_show = np.zeros_like(img)
for mid in np.unique(markers): # 선택한 마커 아이디 갯수 만큼 반복
    color = [int(j) for j in np.random.randint(0,255, 3)]
    colors.append((mid, color))
    marker_show[markers==mid] = color
    coords = np.where(markers==mid)
    x, y = coords[1][0], coords[0][0]
    cv2.putText(marker_show, str(mid), (x+20, y+20), cv2.FONT_HERSHEY_PLAIN, \
                                                             2, (255,255,255))
cv2.imshow('before', marker_show)

# 레이블링이 완성된 마커로 워터 쉐드 적용
markers = cv2.watershed(img, markers)
print("워터쉐드 후:", np.unique(markers))

for mid, color in colors: # 선택한 마커 아이디 갯수 만큼 반복
    marker_show[markers==mid] = color
    coords = np.where(markers==mid)
    if coords[0].size <= 0 : 
        continue
    x, y = coords[1][0], coords[0][0]
    cv2.putText(marker_show, str(mid), (x+20, y+20), cv2.FONT_HERSHEY_PLAIN, \
                                                             2, (255,255,255))
marker_show[markers==-1] = (0,255,0)
cv2.imshow('watershed marker', marker_show)

img[markers==-1] = (0,255,0)
cv2.imshow('watershed', img)

# 동전 추출을 위한 마스킹 생성
mask = np.zeros((rows, cols), np.uint8)
# 배경 마스크 생성
mask[markers!=1] = 255
# 배경 지우기
nobg = cv2.bitwise_and(img, img, mask=mask)
# 동전만 있는 라벨 생성 (배경(1), 경계(-1) 없는)
coin_label = [l for l in np.unique(markers) if (l != 1 and l !=-1)]
# 동전 라벨 순회 하면서 동전 영역만 추출
for i, label in enumerate(coin_label):
    mask[:,:] = 0
    # 해당 동전 추출 마스크 생성
    mask[markers ==label] = 255
    # 동전 영역만 마스크로 추출
    coins = cv2.bitwise_and(img, img, mask=mask)
    # 동전 하나만 있는 곳에서 최외곽 컨투어 추출
    _, contour, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL,\
                                         cv2.CHAIN_APPROX_NONE)
    # 동전을 감싸는 사각형 좌표
    x,y,w,h = cv2.boundingRect(contour[0])
    # 동전 영역만 추출해서 출력
    coin = coins[y:y+h, x:x+w]
    cv2.imshow('coin%d'%(i+1), coin)
    cv2.imwrite('../img/coin_test/coin%d.jpg'%(i+1), coin)
cv2.waitKey()
cv2.destroyAllWindows()

워터쉐드 전: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
워터쉐드 후: [-1  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [16]:
import cv2
import numpy as np

# 이미지 읽기
img = cv2.imread('./traffic_sign3.jpeg')
rows, cols = img.shape[:2]
cv2.imshow('original', img)


# 동전 표면을 흐릿하게 피라미드평균시프트 적용
mean = cv2.pyrMeanShiftFiltering(img, 20, 50)
cv2.imshow('mean', mean)
# 바이너리 이미지 변환
gray = cv2.cvtColor(mean, cv2.COLOR_BGR2GRAY)
gray = cv2.GaussianBlur(gray, (3,3), 0)

_, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
cv2.imshow('thresh', thresh)
# 거리 변환
dst = cv2.distanceTransform(thresh, cv2.DIST_L2, 3)
# 거리 값을 0 ~255로 변환
dst = ( dst / (dst.max() - dst.min()) * 255 ).astype(np.uint8)
cv2.imshow('dst', dst)

# 거리 변환결과에서 로칼 최대 값 구하기
## 팽창 적용(동전 크기 정도의 구조화 요소 필요),
localMx = cv2.dilate(dst, np.ones((50,50), np.uint8))
## 로칼 최대 값 저장 할 배열 생성
lm = np.zeros((rows, cols), np.uint8)
## 팽창 적용전 이미지와 같은 픽셀이 로컬 최대 값이므로 255로 설정
lm[(localMx==dst) & (dst != 0)] = 255
cv2.imshow('localMx', lm)

# 로컬 최대값으로 색 채우기
## 로컬 최대 값이 있는 좌표 구하기
seeds = np.where(lm ==255)
seed = np.stack( (seeds[1], seeds[0]), axis=-1)
## 색 채우기를 위한 채우기 마스크 생성
fill_mask = np.zeros((rows+2, cols+2), np.uint8)
for x,y in seed:
    ## 로칼 최대값을 시드로해서 평균 시프트 영상에 색채우기 
    ret = cv2.floodFill(mean, fill_mask, (x,y), (255,255,255), \
                                            (10,10,10), (10,10,10))
cv2.imshow('floodFill', mean)

# 색 채우기 적용한 영상에 다시 거리 변환 적용
gray = cv2.cvtColor(mean, cv2.COLOR_BGR2GRAY)
gray = cv2.GaussianBlur(gray, (5,5), 0)

ret, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
dst = cv2.distanceTransform(thresh, cv2.DIST_L2, 5)
dst = ( (dst / (dst.max() - dst.min())) * 255 ).astype(np.uint8)
cv2.imshow('dst2', dst)

# 거리 변환 결과값의 절반 이상을 차지한 영역은 확실한 전경으로 설정
ret, sure_fg = cv2.threshold(dst, 0.5*dst.max(), 255,0)
cv2.imshow('sure_fg', sure_fg)

# 거리 변환 결과를 반전해서 확실한 배경 찾기
_, bg_th = cv2.threshold(dst, 0.3*dst.max(),  255, cv2.THRESH_BINARY_INV)
bg_dst = cv2.distanceTransform(bg_th, cv2.DIST_L2, 5)
bg_dst = ( (bg_dst / (bg_dst.max() - bg_dst.min())) * 255 ).astype(np.uint8)
ret, sure_bg = cv2.threshold(bg_dst, 0.3*bg_dst.max(), 255,cv2.THRESH_BINARY)
cv2.imshow('sure_bg', sure_bg)


# 불확실한 영역 설정 : 확실한 배경을 반전해서 확실한 전경을 빼기
ret, inv_sure_bg = cv2.threshold(sure_bg, 127, 255,cv2.THRESH_BINARY_INV)
unkown = cv2.subtract(inv_sure_bg, sure_fg)
cv2.imshow('unkown', unkown)

# 연결된 요소 레이블링
_, markers = cv2.connectedComponents(sure_fg)

# 레이블링을 1씩 증가 시키고 0번 레이블 알 수 없는 영역을 0번 레이블로 설정
markers = markers+1
markers[unkown ==255] = 0
print("워터쉐드 전:", np.unique(markers))
colors = []
marker_show = np.zeros_like(img)
for mid in np.unique(markers): # 선택한 마커 아이디 갯수 만큼 반복
    color = [int(j) for j in np.random.randint(0,255, 3)]
    colors.append((mid, color))
    marker_show[markers==mid] = color
    coords = np.where(markers==mid)
    x, y = coords[1][0], coords[0][0]
    cv2.putText(marker_show, str(mid), (x+20, y+20), cv2.FONT_HERSHEY_PLAIN, \
                                                             2, (255,255,255))
cv2.imshow('before', marker_show)

# 레이블링이 완성된 마커로 워터 쉐드 적용
markers = cv2.watershed(img, markers)
print("워터쉐드 후:", np.unique(markers))

for mid, color in colors: # 선택한 마커 아이디 갯수 만큼 반복
    marker_show[markers==mid] = color
    coords = np.where(markers==mid)
    if coords[0].size <= 0 : 
        continue
    x, y = coords[1][0], coords[0][0]
    cv2.putText(marker_show, str(mid), (x+20, y+20), cv2.FONT_HERSHEY_PLAIN, \
                                                             2, (255,255,255))
marker_show[markers==-1] = (0,255,0)
cv2.imshow('watershed marker', marker_show)

img[markers==-1] = (0,255,0)
cv2.imshow('watershed', img)

# 동전 추출을 위한 마스킹 생성
mask = np.zeros((rows, cols), np.uint8)
# 배경 마스크 생성
mask[markers!=1] = 255
# 배경 지우기
nobg = cv2.bitwise_and(img, img, mask=mask)
# 동전만 있는 라벨 생성 (배경(1), 경계(-1) 없는)
coin_label = [l for l in np.unique(markers) if (l != 1 and l !=-1)]
# 동전 라벨 순회 하면서 동전 영역만 추출
for i, label in enumerate(coin_label):
    mask[:,:] = 0
    # 해당 동전 추출 마스크 생성
    mask[markers ==label] = 255
    # 동전 영역만 마스크로 추출
    coins = cv2.bitwise_and(img, img, mask=mask)
    # 동전 하나만 있는 곳에서 최외곽 컨투어 추출
    _, contour, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL,\
                                         cv2.CHAIN_APPROX_NONE)
    # 동전을 감싸는 사각형 좌표
    x,y,w,h = cv2.boundingRect(contour[0])
    # 동전 영역만 추출해서 출력
    coin = coins[y:y+h, x:x+w]
    cv2.imshow('sign%d'%(i+1), coin)
    cv2.imwrite('../img/traffic_test/sign%d.jpg'%(i+1), coin)
cv2.waitKey()
cv2.destroyAllWindows()

워터쉐드 전: [0 1 2 3 4]
워터쉐드 후: [-1  1  2  3  4]


In [1]:
# 템플릿 매칭으로 객체 위치 검출

import cv2
import numpy as np

# 입력 이미지와 템플릿 이미지 읽기
img = cv2.imread('./img/figures.jpg')
cv2.imshow('img', img)
template = cv2.imread('./img/taekwonv1.jpg')
# print(template.shape) # (444, 400, 3)
th, tw = template.shape[:2]
cv2.imshow('template', template)

# 세 가지 매칭 메서드 순회
methods = [
    'cv2.TM_CCOEFF_NORMED',
    'cv2.TM_CCORR_NORMED',
    'cv2.TM_SQDIFF_NORMED'
]

for i, method_name in enumerate(methods) :
    img_draw = img.copy()
    method = eval(method_name)
    # 템플릿 매칭
    res = cv2.matchTemplate(img, template, method)
    # 최대, 최소 값과 그 좌표 구하기
    min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(res)
    print(method_name, min_val, max_val, min_loc, max_loc)
    
    # TM_SQDIFF의 경우 최소 값이 좋은 매칭, 나머지는 그 반대
    if method in [cv2.TM_SQDIFF, cv2.TM_SQDIFF_NORMED] :
        top_left = min_loc
        match_val = min_val
    else :
        top_left = max_loc
        match_val = min_val
    
    # 매칭 좌표를 구해서 사각형 표시
    bottom_right = (top_left[0] + tw, top_left[1] + th)
    cv2.rectangle(img_draw, top_left, bottom_right, (0, 0, 255), 2)
    
    # 매칭 포인트 표시
    cv2.putText(img_draw, str(match_val), top_left, cv2.FONT_HERSHEY_PLAIN, 2, (0, 255, 0), 1, cv2.LINE_AA)
    
    cv2.imshow(method_name, img_draw)

cv2.waitKey()
cv2.destroyAllWindows()

cv2.TM_CCOEFF_NORMED -0.1780262589454651 0.513192355632782 (42, 0) (208, 43)
cv2.TM_CCORR_NORMED 0.8273324370384216 0.9238021373748779 (85, 6) (208, 43)
cv2.TM_SQDIFF_NORMED 0.1702832579612732 0.36860838532447815 (208, 43) (86, 7)


In [5]:
import cv2
import numpy as np

# 입력 이미지와 템플릿 이미지 읽기
img = cv2.imread('./sample2_86.jpg')
print(img.shape)
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

(1080, 1920, 3)


In [6]:
import cv2
import numpy as np

# 입력 이미지와 템플릿 이미지 읽기
img = cv2.imread('./sample2_86.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))
cv2.imshow('img', img)
template = cv2.imread('./traffic_sign4.png')
template = cv2.resize(template, (template.shape[1]//2, template.shape[0]//2))
th, tw = template.shape[:2]
cv2.imshow('template', template)

# 세 가지 매칭 메서드 순회
methods = [
    'cv2.TM_CCOEFF_NORMED',
    'cv2.TM_CCORR_NORMED',
    'cv2.TM_SQDIFF_NORMED'
]

for i, method_name in enumerate(methods) :
    img_draw = img.copy()
    method = eval(method_name)
    # 템플릿 매칭
    res = cv2.matchTemplate(img, template, method)
    # 최대, 최소 값과 그 좌표 구하기
    min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(res)
    print(method_name, min_val, max_val, min_loc, max_loc)
    
    # TM_SQDIFF의 경우 최소 값이 좋은 매칭, 나머지는 그 반대
    if method in [cv2.TM_SQDIFF, cv2.TM_SQDIFF_NORMED] :
        top_left = min_loc
        match_val = min_val
    else :
        top_left = max_loc
        match_val = min_val
    
    # 매칭 좌표를 구해서 사각형 표시
    bottom_right = (top_left[0] + tw, top_left[1] + th)
    cv2.rectangle(img_draw, top_left, bottom_right, (0, 0, 255), 2)
    
    # 매칭 포인트 표시
    cv2.putText(img_draw, str(match_val), top_left, cv2.FONT_HERSHEY_PLAIN, 2, (0, 255, 0), 1, cv2.LINE_AA)
    
    cv2.imshow(method_name, img_draw)

cv2.waitKey()
cv2.destroyAllWindows()

cv2.TM_CCOEFF_NORMED -0.5421289205551147 0.4863550066947937 (744, 91) (33, 394)
cv2.TM_CCORR_NORMED 0.6033899188041687 0.9303292632102966 (36, 238) (352, 41)
cv2.TM_SQDIFF_NORMED 0.13938568532466888 1.0 (352, 41) (467, 0)


In [4]:
# 해리스 코너 검출

import cv2
import numpy as np

img = cv2.imread('./img/house.jpg')
# cv2.imshow('img', img)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# cv2.imshow('gray', gray)

corner = cv2.cornerHarris(gray, 2, 3, 0.04)
print(len(corner)) # 350
# print(corner)
# 변화량 결과의 최대 값 10% 이상의 좌표 구하기
coord = np.where(corner>0.1*corner.max())
# print(coord[1])
# print(coord[0])
coord = np.stack((coord[1], coord[0]), axis = -1)
print(coord)

# 코너 좌표에 동그라미 그리기
for x, y in coord :
    cv2.circle(img, (x, y), 5, (0, 0, 255), 1, cv2.LINE_AA)

# 변화량을 영상으로 표현하기 위해서 0 ~ 255로 정규화
corner_norm = cv2.normalize(corner, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)
# 화면에 출력
corner_norm = cv2.cvtColor(corner_norm, cv2.COLOR_GRAY2BGR)
merged = np.hstack((corner_norm, img))

cv2.imshow('Harris corner', merged)
cv2.waitKey()
cv2.destroyAllWindows()

350
[[529 198]
 [529 199]
 [530 199]
 [529 200]
 [530 200]
 [529 201]
 [530 201]
 [529 202]
 [529 203]
 [530 203]
 [529 204]
 [529 205]
 [133 211]
 [133 212]
 [302 235]
 [256 236]
 [268 236]
 [192 242]
 [194 246]
 [195 247]
 [196 247]
 [195 248]
 [197 250]
 [255 254]
 [267 254]
 [288 254]
 [289 254]
 [302 254]
 [268 257]
 [286 257]
 [506 265]
 [446 273]
 [529 273]
 [451 274]
 [470 274]
 [529 274]
 [447 275]
 [322 276]
 [323 276]
 [ 15 280]
 [ 14 281]
 [ 15 281]
 [ 86 281]
 [102 282]
 [103 282]
 [ 87 283]
 [102 283]
 [103 283]
 [ 85 284]
 [215 284]
 [ 87 285]
 [255 285]
 [296 285]
 [  7 286]
 [  8 286]
 [  7 287]
 [  8 287]
 [417 291]
 [417 292]
 [417 294]
 [418 294]
 [417 295]
 [  2 297]
 [  3 297]
 [  4 297]
 [  3 298]
 [454 298]
 [455 298]
 [  2 299]
 [  3 299]
 [  4 299]
 [362 300]
 [ 84 302]
 [  0 303]
 [  1 303]
 [ 84 303]
 [ 94 303]
 [451 303]
 [452 303]
 [  0 304]
 [  1 304]
 [477 304]
 [478 304]
 [ 95 307]
 [295 308]
 [293 313]
 [313 313]
 [313 314]
 [365 317]
 [366 317]
 [387 

In [9]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg')
# cv2.imshow('img', img)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# cv2.imshow('gray', gray)

corner = cv2.cornerHarris(gray, 2, 3, 0.04)
# 변화량 결과의 최대 값 10% 이상의 좌표 구하기
coord = np.where(corner>0.1*corner.max())
coord = np.stack((coord[1], coord[0]), axis = -1)

# 코너 좌표에 동그라미 그리기
for x, y in coord :
    cv2.circle(img, (x, y), 5, (0, 0, 255), 1, cv2.LINE_AA)

# 변화량을 영상으로 표현하기 위해서 0 ~ 255로 정규화
corner_norm = cv2.normalize(corner, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)
# 화면에 출력
corner_norm = cv2.cvtColor(corner_norm, cv2.COLOR_GRAY2BGR)
merged = np.hstack((corner_norm, img))

cv2.imshow('Harris corner', merged)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
# 시-토마시 코너 검출

import cv2
import numpy as np

img = cv2.imread('./img/house.jpg')
gray  = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

corners = cv2.goodFeaturesToTrack(gray, 80, 0.01, 10)
# 실수 좌표를 정수 좌표로 반환
corners = np.int32(corners)
# print(corners)

# 좌표에 동그라미 표시
for corner in corners :
    x, y = corner[0]
    cv2.circle(img, (x, y), 5, (0, 0, 255), 1, cv2.LINE_AA)
    
cv2.imshow('Corners', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg')
gray  = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

corners = cv2.goodFeaturesToTrack(gray, 10, 0.01, 10)
# 실수 좌표를 정수 좌표로 반환
corners = np.int32(corners)
# print(corners)

# 좌표에 동그라미 표시
for corner in corners :
    x, y = corner[0]
    cv2.circle(img, (x, y), 5, (0, 0, 255), 1, cv2.LINE_AA)
    
cv2.imshow('Corners', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
# GFTTDetector로 키 포인트 검출

import cv2
import numpy as np

img = cv2.imread('./img/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Good feature to trac 검출기 생성
gtff = cv2.GFTTDetector_create()
# 키 포인트 검출
keypoints = gtff.detect(gray, None)
# 키 포인트 그리기
img_draw = cv2.drawKeypoints(img, keypoints, None)

cv2.imshow('GFTTDetector', img_draw)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Good feature to trac 검출기 생성
gtff = cv2.GFTTDetector_create()
# 키 포인트 검출
keypoints = gtff.detect(gray, None)
# 키 포인트 그리기
img_draw = cv2.drawKeypoints(img, keypoints, None)

cv2.imshow('GFTTDetector', img_draw)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
# FAST로 키 포인트 검출

import cv2
import numpy as np

img = cv2.imread('./img/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# FAST 특징 검출기 생성
fast = cv2.FastFeatureDetector_create(50)
keypoints = fast.detect(gray, None)
img = cv2.drawKeypoints(img, keypoints, None)

cv2.imshow('FAST', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# FAST 특징 검출기 생성
fast = cv2.FastFeatureDetector_create(100)
keypoints = fast.detect(gray, None)
img = cv2.drawKeypoints(img, keypoints, None)

cv2.imshow('FAST', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [2]:
# SimpleBlobDetector 검출기

import cv2
import numpy as np

img = cv2.imread('./img/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# SimpleBlobDetector 생성
detector = cv2.SimpleBlobDetector_create()
# 키 포인트 검출
keypoints = detector.detect(gray)

img = cv2.drawKeypoints(img, keypoints, None, (0, 0, 255), flags = cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow('Blob', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# SimpleBlobDetector 생성
detector = cv2.SimpleBlobDetector_create()
# 키 포인트 검출
keypoints = detector.detect(gray)

img = cv2.drawKeypoints(img, keypoints, None, (0, 0, 255), flags = cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow('Blob', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
# 필터 옵션으로 생성한 SimpleBlobDetector 검출기

import cv2
import numpy as np

img = cv2.imread('./img/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# BLOB 검출 필터 파라미터 생성
params = cv2.SimpleBlobDetector_Params()

# 경계 값 조정
params.minThreshold = 10
params.maxThreshold = 240
params.thresholdStep = 5
# 면적 필터를 켜고 최소 값 지정
params.filterByArea = True
params.minArea = 200

# 컬러, 블록 비율, 원형 비율 필터 옵션 끄기
params.filterByColor = False
params.filterByConvexity = False
params.filterByInertia = False
params.filterByCircularity = False

# 필터 파라미터로 BLOB 검출기 생성
detector = cv2.SimpleBlobDetector_create(params)
# 키 포인트 검출
keypoints = detector.detect(gray)
# 키 포인트 그리기
img_draw = cv2.drawKeypoints(img, keypoints, None, None, cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow('Blob with Params', img_draw)
cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# BLOB 검출 필터 파라미터 생성
params = cv2.SimpleBlobDetector_Params()

# 경계 값 조정
params.minThreshold = 50
params.maxThreshold = 200
params.thresholdStep = 5
# 면적 필터를 켜고 최소 값 지정
params.filterByArea = True
params.minArea = 1000

# 컬러, 볼록 비율, 원형 비율 필터 옵션 끄기
params.filterByColor = False
params.filterByConvexity = False
params.filterByInertia = False
params.filterByCircularity = False

# 필터 파라미터로 BLOB 검출기 생성
detector = cv2.SimpleBlobDetector_create(params)
# 키 포인트 검출
keypoints = detector.detect(gray)
# 키 포인트 그리기
img_draw = cv2.drawKeypoints(img, keypoints, None, None, cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow('Blob with Params', img_draw)
cv2.waitKey()
cv2.destroyAllWindows()

In [23]:
# SIFT로 키 포인트 및 디스크립터 추출

import cv2
import numpy as np

img = cv2.imread('./img/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# SIFT 추출기 생성
sift = cv2.xfeatures2d.SIFT_create()
# 키 포인트 검출과 서술자 계산
keypoints, descriptor = sift.detectAndCompute(gray, None)
print('keypoint : ', len(keypoints), 'descriptor : ', descriptor.shape)
print(descriptor)

# 키 포인트 그리기
img_draw = cv2.drawKeypoints(img, keypoints, None, flags = cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

# 결과 출력
cv2.imshow('SIFT', img_draw)
cv2.waitKey()
cv2.destroyAllWindows()

error: OpenCV(3.4.7) /io/opencv_contrib/modules/xfeatures2d/src/sift.cpp:1207: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'create'


In [24]:
# ORB로 키 포인트 및 디스크립터 추출

import cv2
import numpy as np

img = cv2.imread('./img/house.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# ORB 추출기 생성
orb = cv2.ORB_create()
# 키 포인트 검출과 서술자 계산
keypoints, descriptor = orb.detectAndCompute(img, None)
# 키 포인트 그리기
img_draw = cv2.drawKeypoints(img, keypoints, None, flags = cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow('ORB', img_draw)
cv2.waitKey()
cv2.destroyAllWindows()

In [25]:
import cv2
import numpy as np

img = cv2.imread('./traffic_sign3.jpeg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# ORB 추출기 생성
orb = cv2.ORB_create()
# 키 포인트 검출과 서술자 계산
keypoints, descriptor = orb.detectAndCompute(img, None)
# 키 포인트 그리기
img_draw = cv2.drawKeypoints(img, keypoints, None, flags = cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow('ORB', img_draw)
cv2.waitKey()
cv2.destroyAllWindows()

In [33]:
# BFMatcher와 ORB로 매칭

import cv2
import numpy as np

img1 = cv2.imread('./img/taekwonv1.jpg')
img2 = cv2.imread('./img/figures.jpg')
gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# ORB 디스크립터 추출기 생성
detector = cv2.ORB_create()
# print(detector)
# 각 영상에 대해 키 포인트와 디스크립터 추출
kp1, desc1 = detector.detectAndCompute(gray1, None)
# print(kp1, desc1)

kp2, desc2 = detector.detectAndCompute(gray2, None)
# print(kp2, desc2)

# BFMatcher 생성, 해밍 거리, 상호 체크
matcher = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck = True)
# 매칭 계산
matches = matcher.match(desc1, desc2)
# 매칭 결과 그리기
res = cv2.drawMatches(img1, kp1, img2, kp2, matches, None, flags = cv2.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS)

cv2.imshow('BFMatchers + ORB', res)
cv2.waitKey()
cv2.destroyAllWindows()

In [30]:
import cv2
import numpy as np

img1 = cv2.imread('./traffic_sign4.png')
# img1 = cv2.GaussianBlur(img1, (3, 3), 0)

img2 = cv2.imread('./traffic_sign3.jpeg')
# img2 = cv2.GaussianBlur(img2, (3, 3), 0)

gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# ORB 디스크립터 추출기 생성
detector = cv2.ORB_create()
# 각 영상에 대해 키 포인트와 디스크립터 추출
kp1, desc1 = detector.detectAndCompute(gray1, None)
kp2, desc2 = detector.detectAndCompute(gray2, None)

# BFMatcher 생성, 해밍 거리, 상호 체크
matcher = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck = True)
# 매칭 계산
matches = matcher.match(desc1, desc2)
# 매칭 결과 그리기
res = cv2.drawMatches(img1, kp1, img2, kp2, matches, None, flags = cv2.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS)

cv2.imshow('BFMatchers + ORB', res)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
# 매칭점 원근 변환으로 영역 찾기

import cv2
import numpy as np

img1 = cv2.imread('./img/taekwonv1.jpg')
img2 = cv2.imread('./img/figures.jpg')
gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# ORB, BF-Hamming로 knnMatch
detector = cv2.ORB_create()
kp1, desc1 = detector.detectAndCompute(gray1, None)
kp2, desc2 = detector.detectAndCompute(gray2, None)
matcher = cv2.BFMatcher(cv2.NORM_HAMMING2)
matches = matcher.knnMatch(desc1, desc2, 2)

# 이웃 거리의 75%로 좋은 매칭점 추출
ratio = 0.75
good_matches = [first for first, second in matches if first.distance < second.distance * ratio]
print('good matches : %d/%d' %(len(good_matches), len(matches)))

# 좋은 매칭점의 queryIdx로 원본 영상의 좌표 구하기
src_pts = np.float32()

In [37]:
import cv2, numpy as np

img1 = cv2.imread('./img/taekwonv1.jpg')
img2 = cv2.imread('./img/figures.jpg')
gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# ORB, BF-Hamming 로 knnMatch  ---①
detector = cv2.ORB_create()
kp1, desc1 = detector.detectAndCompute(gray1, None)
kp2, desc2 = detector.detectAndCompute(gray2, None)
matcher = cv2.BFMatcher(cv2.NORM_HAMMING2)
matches = matcher.knnMatch(desc1, desc2, 2)

# 이웃 거리의 75%로 좋은 매칭점 추출---②
ratio = 0.75
good_matches = [first for first,second in matches \
                    if first.distance < second.distance * ratio]
print('good matches:%d/%d' %(len(good_matches),len(matches)))

# 좋은 매칭점의 queryIdx로 원본 영상의 좌표 구하기 ---③
src_pts = np.float32([ kp1[m.queryIdx].pt for m in good_matches ])
# 좋은 매칭점의 trainIdx로 대상 영상의 좌표 구하기 ---④
dst_pts = np.float32([ kp2[m.trainIdx].pt for m in good_matches ])
# 원근 변환 행렬 구하기 ---⑤
mtrx, mask = cv2.findHomography(src_pts, dst_pts)
# 원본 영상 크기로 변환 영역 좌표 생성 ---⑥
h,w, = img1.shape[:2]
pts = np.float32([ [[0,0]],[[0,h-1]],[[w-1,h-1]],[[w-1,0]] ])
# 원본 영상 좌표를 원근 변환  ---⑦
dst = cv2.perspectiveTransform(pts,mtrx)
# 변환 좌표 영역을 대상 영상에 그리기 ---⑧
img2 = cv2.polylines(img2,[np.int32(dst)],True,255,3, cv2.LINE_AA)

# 좋은 매칭 그려서 출력 ---⑨
res = cv2.drawMatches(img1, kp1, img2, kp2, good_matches, None, \
                    flags=cv2.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS)
cv2.imshow('Matching Homography', res)
cv2.waitKey()
cv2.destroyAllWindows()

good matches:26/500


In [38]:
import cv2, numpy as np

img1 = cv2.imread('./traffic_sign4.png')
img2 = cv2.imread('./traffic_sign3.jpeg')
gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# ORB, BF-Hamming 로 knnMatch  ---①
detector = cv2.ORB_create()
kp1, desc1 = detector.detectAndCompute(gray1, None)
kp2, desc2 = detector.detectAndCompute(gray2, None)
matcher = cv2.BFMatcher(cv2.NORM_HAMMING2)
matches = matcher.knnMatch(desc1, desc2, 2)

# 이웃 거리의 75%로 좋은 매칭점 추출---②
ratio = 0.75
good_matches = [first for first,second in matches \
                    if first.distance < second.distance * ratio]
print('good matches:%d/%d' %(len(good_matches),len(matches)))

# 좋은 매칭점의 queryIdx로 원본 영상의 좌표 구하기 ---③
src_pts = np.float32([ kp1[m.queryIdx].pt for m in good_matches ])
# 좋은 매칭점의 trainIdx로 대상 영상의 좌표 구하기 ---④
dst_pts = np.float32([ kp2[m.trainIdx].pt for m in good_matches ])
# 원근 변환 행렬 구하기 ---⑤
mtrx, mask = cv2.findHomography(src_pts, dst_pts)
# 원본 영상 크기로 변환 영역 좌표 생성 ---⑥
h,w, = img1.shape[:2]
pts = np.float32([ [[0,0]],[[0,h-1]],[[w-1,h-1]],[[w-1,0]] ])
# 원본 영상 좌표를 원근 변환  ---⑦
dst = cv2.perspectiveTransform(pts,mtrx)
# 변환 좌표 영역을 대상 영상에 그리기 ---⑧
img2 = cv2.polylines(img2,[np.int32(dst)],True,255,3, cv2.LINE_AA)

# 좋은 매칭 그려서 출력 ---⑨
res = cv2.drawMatches(img1, kp1, img2, kp2, good_matches, None, \
                    flags=cv2.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS)
cv2.imshow('Matching Homography', res)
cv2.waitKey()
cv2.destroyAllWindows()

good matches:0/233


error: OpenCV(3.4.7) /io/opencv/modules/calib3d/src/fundam.cpp:372: error: (-5:Bad argument) The input arrays should be 2D or 3D point sets in function 'findHomography'
