### 객체 검출 후 이미지 저장

In [ ]:
import cv2
import numpy as np
import matplotlib.pylab as plt


# 색상별 영역 지정
red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./frame3.png')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), interpolation = cv2.INTER_AREA)
h, w = img.shape[:2]
# cv2. imshow('img', img)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)
# print(hsv)
img = cv2.bilateralFilter(img,9,105,105)
r, g, b = cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
# equalize = cv2.merge((r,g,b))
# cv2.imshow('equalize', equalize)
equalize = cv2.merge((r,g,b))
img = equalize

# 색상에 따른 마스크 생성
mask_red1 = cv2.inRange(hsv, red1, red2)
cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

# 색상별 마스크로 색상만 추출
res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red2)

for idx, centroid in enumerate(centroids) :
    if stats[idx][0] == 0 and stats[idx][1] == 0 :
        continue
    
    if np.any(np.isnan(centroid)) :
        continue
    
    x, y, w, h, area = stats[idx]
    # print(x, y, w, h, area)
    # print('-'*20)
    centerX, centerY = int(centroid[0]), int(centroid[1])

    # if area > 50 and abs(w-h) < 10 :
    if area > 50 and abs(w-h) < 5 : 
        # cv2.circle(img, (centerX, centerY), 10, (255, 0, 0), 2)
        print(x, y, w, h)
        # cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 1)
        # 원 검출
        detected_img = img[y:y+h, x:x+w]
        gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
        # blur = cv2.GaussianBlur(gray_detected_img, (3, 3), 0)
        print(gray_detected_img.shape)
        gray_detected_img = cv2.resize(gray_detected_img, (gray_detected_img.shape[1]*5, gray_detected_img.shape[0]*5))
        # circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1.5, 30, param1 = 570)
        circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=50, param2=30, minRadius=10, maxRadius=0)
        print(circles)
        if circles is not None :
            circles = np.uint16(np.around(circles))
            for i in circles[0, :] :
                cv2.circle(gray_detected_img, (i[0], i[1]), i[2], (0, 255, 0), 2)
                cv2.circle(gray_detected_img, (i[0], i[1]), 2, (0, 0, 255), 5)
                cv2.imshow('gray_detected_img{}'.format(idx), gray_detected_img)
                cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 1)
                cv2.imwrite()

# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
# cv2.imshow('res_red', res_red)

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
import cv2
import numpy as np
import matplotlib.pylab as plt

# 색상별 영역 지정
red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./frame3.png')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), interpolation = cv2.INTER_AREA)
img2 = img.copy()
h, w = img.shape[:2]
# cv2. imshow('img', img)
# cv2. imshow('img2', img2)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)
# print(hsv)
img = cv2.bilateralFilter(img,9,105,105)
r, g, b = cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
# equalize = cv2.merge((r,g,b))
# cv2.imshow('equalize', equalize)
equalize = cv2.merge((equalize1, equalize2, equalize3))
img = equalize

# 색상에 따른 마스크 생성
mask_red1 = cv2.inRange(hsv, red1, red2)
cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

# 색상별 마스크로 색상만 추출
res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red2)

for idx, centroid in enumerate(centroids) :
    if stats[idx][0] == 0 and stats[idx][1] == 0 :
        continue
    
    if np.any(np.isnan(centroid)) :
        continue
    
    x, y, w, h, area = stats[idx]
    # print(x, y, w, h, area)
    # print('-'*20)
    centerX, centerY = int(centroid[0]), int(centroid[1])

    # if area > 50 and abs(w-h) < 10 :
    if area > 50 and abs(w-h) < 5 : 
        # cv2.circle(img, (centerX, centerY), 10, (255, 0, 0), 2)
        print(x, y, w, h)
        # cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 1)
        # 원 검출
        detected_img = img[y:y+h, x:x+w]
        gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
        # blur = cv2.GaussianBlur(gray_detected_img, (3, 3), 0)
        print(gray_detected_img.shape)
        gray_detected_img = cv2.resize(gray_detected_img, (gray_detected_img.shape[1]*5, gray_detected_img.shape[0]*5))
        # circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1.5, 30, param1 = 570)
        circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=50, param2=30, minRadius=10, maxRadius=0)
        print(circles)
        if circles is not None :
            circles = np.uint16(np.around(circles))
            for i in circles[0, :] :
                cv2.circle(gray_detected_img, (i[0], i[1]), i[2], (0, 255, 0), 2)
                cv2.circle(gray_detected_img, (i[0], i[1]), 2, (0, 0, 255), 5)
                cv2.imshow('gray_detected_img{}'.format(idx), gray_detected_img)
                cv2.rectangle(img2, (x, y), (x+w, y+h), (255, 0, 0), 1)
                # cv2.imwrite()

# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
# cv2.imshow('res_red', res_red)

cv2.imshow('img2', img2)
cv2.waitKey()
cv2.destroyAllWindows()

343 126 23 23
(23, 23)
[[[56.5 55.5 53.8]]]
712 154 17 19
(19, 17)
None
456 207 8 12
(12, 8)
None


In [13]:
import cv2
import numpy as np
import matplotlib.pylab as plt

# 색상별 영역 지정
red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./sample6_68.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), interpolation = cv2.INTER_AREA)
img2 = img.copy()
h, w = img.shape[:2]
# cv2. imshow('img', img)
# cv2. imshow('img2', img2)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)
# print(hsv)
img = cv2.bilateralFilter(img,9,105,105)
r, g, b = cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
# equalize = cv2.merge((r,g,b))
# cv2.imshow('equalize', equalize)
equalize = cv2.merge((r,g,b))
img = equalize

# 색상에 따른 마스크 생성
mask_red1 = cv2.inRange(hsv, red1, red2)
cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

# 색상별 마스크로 색상만 추출
res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red2)

for idx, centroid in enumerate(centroids) :
    if stats[idx][0] == 0 and stats[idx][1] == 0 :
        continue
    
    if np.any(np.isnan(centroid)) :
        continue
    
    x, y, w, h, area = stats[idx]
    # print(x, y, w, h, area)
    # print('-'*20)
    centerX, centerY = int(centroid[0]), int(centroid[1])

    # if area > 50 and abs(w-h) < 10 :
    if area > 50 and abs(w-h) < 5 : 
        # cv2.circle(img, (centerX, centerY), 10, (255, 0, 0), 2)
        print(x, y, w, h)
        # cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 1)
        # 원 검출
        detected_img = img[y:y+h, x:x+w]
        gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
        # blur = cv2.GaussianBlur(gray_detected_img, (3, 3), 0)
        print(gray_detected_img.shape)
        gray_detected_img = cv2.resize(gray_detected_img, (gray_detected_img.shape[1]*5, gray_detected_img.shape[0]*5))
        # circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1.5, 30, param1 = 570)
        circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=50, param2=30, minRadius=10, maxRadius=0)
        print(circles)
        if circles is not None :
            circles = np.uint16(np.around(circles))
            for i in circles[0, :] :
                cv2.circle(gray_detected_img, (i[0], i[1]), i[2], (0, 255, 0), 2)
                cv2.circle(gray_detected_img, (i[0], i[1]), 2, (0, 0, 255), 5)
                cv2.imshow('gray_detected_img{}'.format(idx), gray_detected_img)
                cv2.rectangle(img2, (x, y), (x+w, y+h), (255, 0, 0), 1)
                # cv2.imwrite()

# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
# cv2.imshow('res_red', res_red)

cv2.imshow('img2', img2)
cv2.waitKey()
cv2.destroyAllWindows()

380 112 12 13
(13, 12)
None
500 113 13 12
(12, 13)
None
865 161 17 15
(15, 17)
None


In [12]:
import cv2
import numpy as np
import matplotlib.pylab as plt

# 색상별 영역 지정
red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./sample6_81.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), interpolation = cv2.INTER_AREA)
img2 = img.copy()
h, w = img.shape[:2]
# cv2. imshow('img', img)
# cv2. imshow('img2', img2)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)
# print(hsv)
img = cv2.bilateralFilter(img,9,105,105)
r, g, b = cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
# equalize = cv2.merge((r,g,b))
# cv2.imshow('equalize', equalize)
equalize = cv2.merge((r,g,b))
img = equalize

# 색상에 따른 마스크 생성
mask_red1 = cv2.inRange(hsv, red1, red2)
cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

# 색상별 마스크로 색상만 추출
res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red2)

for idx, centroid in enumerate(centroids) :
    if stats[idx][0] == 0 and stats[idx][1] == 0 :
        continue
    
    if np.any(np.isnan(centroid)) :
        continue
    
    x, y, w, h, area = stats[idx]
    # print(x, y, w, h, area)
    # print('-'*20)
    centerX, centerY = int(centroid[0]), int(centroid[1])

    # if area > 50 and abs(w-h) < 10 :
    if area > 30 and abs(w-h) < 5 : 
        # cv2.circle(img, (centerX, centerY), 10, (255, 0, 0), 2)
        print(x, y, w, h)
        # cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 1)
        # 원 검출
        detected_img = img[y:y+h, x:x+w]
        gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
        # blur = cv2.GaussianBlur(gray_detected_img, (3, 3), 0)
        print(gray_detected_img.shape)
        gray_detected_img = cv2.resize(gray_detected_img, (gray_detected_img.shape[1]*5, gray_detected_img.shape[0]*5))
        # circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1.5, 30, param1 = 570)
        circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=50, param2=30, minRadius=10, maxRadius=0)
        print(circles)
        if circles is not None :
            circles = np.uint16(np.around(circles))
            for i in circles[0, :] :
                cv2.circle(gray_detected_img, (i[0], i[1]), i[2], (0, 255, 0), 2)
                cv2.circle(gray_detected_img, (i[0], i[1]), 2, (0, 0, 255), 5)
                cv2.imshow('gray_detected_img{}'.format(idx), gray_detected_img)
                cv2.rectangle(img2, (x, y), (x+w, y+h), (255, 0, 0), 1)
                # cv2.imwrite()

# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
# cv2.imshow('res_red', res_red)

cv2.imshow('img2', img2)
cv2.waitKey()
cv2.destroyAllWindows()

136 293 10 13
(13, 10)
None
183 293 11 8
(8, 11)
None


In [5]:
import cv2
import numpy as np
import matplotlib.pylab as plt

# 색상별 영역 지정
red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

file_name = 'frame2.png'
img = cv2.imread('./' + file_name)
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), interpolation = cv2.INTER_AREA)
img2 = img.copy()
img3 = img.copy()

h, w = img.shape[:2]
# cv2. imshow('img', img)
# cv2. imshow('img2', img2)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)
# print(hsv)
img = cv2.bilateralFilter(img,9,105,105)
r, g, b = cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
# equalize = cv2.merge((r,g,b))
# cv2.imshow('equalize', equalize)
equalize = cv2.merge((equalize1, equalize2, equalize3))
img = equalize

# 색상에 따른 마스크 생성
mask_red1 = cv2.inRange(hsv, red1, red2)
cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

# 색상별 마스크로 색상만 추출
res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red2)

for idx, centroid in enumerate(centroids) :
    if stats[idx][0] == 0 and stats[idx][1] == 0 :
        continue
    
    if np.any(np.isnan(centroid)) :
        continue
    
    x, y, w, h, area = stats[idx]
    # print(x, y, w, h, area)
    # print('-'*20)
    centerX, centerY = int(centroid[0]), int(centroid[1])

    # if area > 50 and abs(w-h) < 10 :
    if area > 50 and abs(w-h) < 5 : 
        # cv2.circle(img, (centerX, centerY), 10, (255, 0, 0), 2)
        print(x, y, w, h)
        # cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 1)
        # 원 검출
        detected_img = img[y:y+h, x:x+w]
        gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
        # blur = cv2.GaussianBlur(gray_detected_img, (3, 3), 0)
        print(gray_detected_img.shape)
        gray_detected_img = cv2.resize(gray_detected_img, (gray_detected_img.shape[1]*5, gray_detected_img.shape[0]*5))
        # circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1.5, 30, param1 = 570)
        circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=50, param2=30, minRadius=10, maxRadius=0)
        print(circles)
        if circles is not None :
            circles = np.uint16(np.around(circles))
            for i in circles[0, :] :
                cv2.circle(gray_detected_img, (i[0], i[1]), i[2], (0, 255, 0), 2)
                cv2.circle(gray_detected_img, (i[0], i[1]), 2, (0, 0, 255), 5)
                cv2.imshow('gray_detected_img{}'.format(idx), gray_detected_img)
                cv2.rectangle(img2, (x, y), (x+w, y+h), (255, 0, 0), 1)
                cv2.imwrite('images/{}_{}.{}'.format(file_name.split('.')[0], idx, file_name.split('.')[1]), img3[y:y+h, x:x+w])

# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
# cv2.imshow('res_red', res_red)

cv2.imshow('img2', img2)
cv2.waitKey()
cv2.destroyAllWindows()

163 149 9 11
(11, 9)
None
85 197 21 20
(20, 21)
[[[49.5 52.5 46.6]]]
207 202 20 19
(19, 20)
[[[47.5 45.5 45.9]]]
324 207 19 19
(19, 19)
[[[43.5 48.5 44.9]]]


In [4]:
# file_name = 'sample1.jpg'
# print(file_name.split('.')[0])
# print(file_name.split('.')[1])

In [7]:
img = cv2.imread('./images/frame2_41.png')
print(img.shape)
img = cv2.resize(img, (64, 64))
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

(19, 19, 3)
