In [5]:
import cv2 # opencv 사용
import numpy as np
image = cv2.imread('./sample3_515.jpg') # 이미지 읽기
# print(image.shape) # (1080, 1920, 3)
image = cv2.resize(image, (image.shape[1]//2, image.shape[0]//2))
mark = np.copy(image) # image 복사

#  BGR 제한 값 설정
blue_threshold = 200
green_threshold = 200
red_threshold = 200
bgr_threshold = [blue_threshold, green_threshold, red_threshold]

# BGR 제한 값보다 작으면 검은색으로
thresholds = (image[:,:,0] < bgr_threshold[0]) \
            | (image[:,:,1] < bgr_threshold[1]) \
            | (image[:,:,2] < bgr_threshold[2])
mark[thresholds] = [0,0,0]

cv2.imshow('white',mark) # 흰색 추출 이미지 출력
cv2.imshow('result',image) # 이미지 출력
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
print(image.shape)

(1080, 1920, 3)


In [22]:
import cv2
import numpy as np

image = cv2.imread('./sample3_515.jpg') # 이미지 읽기
# print(image.shape) # (1080, 1920, 3)
image = cv2.resize(image, (image.shape[1]//2, image.shape[0]//2))
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

# define range of white color in HSV
# change it according to your need!
sensitivity = 70
lower_white = np.array([0, 0, 255-sensitivity])
upper_white = np.array([255, sensitivity, 255])

# Threshold the HSV image to get only white colors
mask = cv2.inRange(hsv, lower_white, upper_white)
# Bitwise-AND mask and original image
res = cv2.bitwise_and(image,image, mask= mask)

cv2.imshow('image',image)
cv2.imshow('mask',mask)
cv2.imshow('res',res)

cv2.waitKey()
cv2.destroyAllWindows()

In [23]:
import cv2
import numpy as np

image = cv2.imread('./sample3_515.jpg') # 이미지 읽기
# print(image.shape) # (1080, 1920, 3)
image = cv2.resize(image, (image.shape[1]//2, image.shape[0]//2))
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

# define range of white color in HSV
# change it according to your need!
sensitivity = 70
lower_white = np.array([0, 0, 255-sensitivity])
upper_white = np.array([255, sensitivity, 255])

red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

# mask_red1 = cv2.inRange(hsv, red1, red2)
# cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
# cv2.imshow('mask_red2', mask_red2)
# mask_red = mask_red1 + mask_red2

# Threshold the HSV image to get only white colors
mask_white = cv2.inRange(hsv, lower_white, upper_white)
# Bitwise-AND mask and original image
mask = mask_red2 + mask_white
res = cv2.bitwise_and(image,image, mask= mask)

cv2.imshow('image',image)
cv2.imshow('mask',mask)
cv2.imshow('res',res)

cv2.waitKey()
cv2.destroyAllWindows()

In [24]:
import cv2
import numpy as np
import matplotlib.pylab as plt


# 색상별 영역 지정
blue1 = np.array([90, 50, 50])
blue2 = np.array([120, 255, 255])

green1 = np.array([45, 50, 50])
green2 = np.array([75, 255, 255])

yellow1 = np.array([20, 50, 50])
yellow2 = np.array([35, 255, 255])

red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./sample3_515.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)
h, w = img.shape[:2]
# cv2. imshow('img', img)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)

img = cv2.bilateralFilter(img,9,105,105)
r,g,b=cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
# equalize=cv2.merge((r,g,b))
# cv2.imshow('equalize', equalize)
equalize=cv2.merge((r,g,b))

# 색상에 따른 마스크 생성
mask_blue = cv2.inRange(hsv, blue1, blue2)
mask_green = cv2.inRange(hsv, green1, green2)
mask_yellow = cv2.inRange(hsv, yellow1, yellow2)
mask_red1 = cv2.inRange(hsv, red1, red2)
cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

kernel = np.ones((11, 11), np.uint8)
mask_red = cv2.morphologyEx(mask_red, cv2.MORPH_OPEN, kernel)
mask_red = cv2.morphologyEx(mask_red, cv2.MORPH_CLOSE, kernel)

# 색상별 마스크로 색상만 추출
res_blue = cv2.bitwise_and(img, img, mask = mask_blue)
res_green = cv2.bitwise_and(img, img, mask = mask_green)
res_yellow = cv2.bitwise_and(img, img, mask = mask_yellow)

res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

# 연결 요소 레이블링
# : 연결된 요소들끼리 분리하는 방법
# : 바이너리 스케일 이미지에서 픽셀 값이 0으로 끊어지지 않는 영역끼리 같은 값을 부여해서 분리하는 방법
# retval, labels, stats, centroids 
#                 = cv2.connectedComponentsWithStats(src[, labels, stats, centroids, connectivity, ltype])
# retval : 레이블 개수
# labels : 레이블링된 입력 영상과 같은 크기의 배열
# src : 입력 영상, 바이너리 스케일 이미지
# stats : x좌표, y좌표, 폭, 높이, 넓이
# centroids : 각 레이블의 중심점 좌표

numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red)
print(numOfLabels)
print(img_label)
print(stats)
print(centroids)

for idx, centroid in enumerate(centroids) :
    if stats[idx][0] == 0 and stats[idx][1] == 0 :
        continue
    
    if np.any(np.isnan(centroid)) :
        continue
    
    x, y, w, h, area = stats[idx]
    centerX, centerY = int(centroid[0]), int(centroid[1])

    if area > 50 :
        cv2.circle(img, (centerX, centerY), 10, (0, 0, 255), 10)
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 255))

# cv2.imshow('res_blue', res_blue)
# cv2.imshow('res_green', res_green)
# cv2.imshow('res_yellow', res_yellow)
# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
cv2.imshow('res_red', res_red)

cv2. imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

9
[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[     0      0    960    540 499712]
 [   721      0     51    115   2716]
 [   780      0     15     13    188]
 [   896      0     64    141   6955]
 [   740    151     74    255   7960]
 [   688    292     12     12    143]
 [   408    323     22     11    242]
 [   492    324     21     12    248]
 [   102    348     15     16    236]]
[[467.10176262 272.97623631]
 [751.71502209  66.55081001]
 [786.7393617    5.88829787]
 [930.4813803   60.90208483]
 [771.9491206  302.30025126]
 [693.46153846 297.53846154]
 [418.5        328.        ]
 [502.06854839 329.45564516]
 [108.94491525 355.62288136]]


In [12]:
import cv2
import numpy as np
import matplotlib.pylab as plt


# 색상별 영역 지정
blue1 = np.array([90, 50, 50])
blue2 = np.array([120, 255, 255])

green1 = np.array([45, 50, 50])
green2 = np.array([75, 255, 255])

yellow1 = np.array([20, 50, 50])
yellow2 = np.array([35, 255, 255])

red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./sample3_515.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)
h, w = img.shape[:2]
# cv2. imshow('img', img)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)

img = cv2.bilateralFilter(img,9,105,105)
r,g,b=cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
# equalize=cv2.merge((r,g,b))
# cv2.imshow('equalize', equalize)
equalize=cv2.merge((r,g,b))

# 색상에 따른 마스크 생성
mask_blue = cv2.inRange(hsv, blue1, blue2)
mask_green = cv2.inRange(hsv, green1, green2)
mask_yellow = cv2.inRange(hsv, yellow1, yellow2)
mask_red1 = cv2.inRange(hsv, red1, red2)
cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

kernel = np.ones((11, 11), np.uint8)
mask_red1 = cv2.morphologyEx(mask_red1, cv2.MORPH_OPEN, kernel)
mask_red1 = cv2.morphologyEx(mask_red1, cv2.MORPH_CLOSE, kernel)
mask_red2 = cv2.morphologyEx(mask_red2, cv2.MORPH_OPEN, kernel)
mask_red2 = cv2.morphologyEx(mask_red2, cv2.MORPH_CLOSE, kernel)

# 색상별 마스크로 색상만 추출
res_blue = cv2.bitwise_and(img, img, mask = mask_blue)
res_green = cv2.bitwise_and(img, img, mask = mask_green)
res_yellow = cv2.bitwise_and(img, img, mask = mask_yellow)

res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

# 연결 요소 레이블링
# : 연결된 요소들끼리 분리하는 방법
# : 바이너리 스케일 이미지에서 픽셀 값이 0으로 끊어지지 않는 영역끼리 같은 값을 부여해서 분리하는 방법
# retval, labels, stats, centroids 
#                 = cv2.connectedComponentsWithStats(src[, labels, stats, centroids, connectivity, ltype])
# retval : 레이블 개수
# labels : 레이블링된 입력 영상과 같은 크기의 배열
# src : 입력 영상, 바이너리 스케일 이미지
# stats : x좌표, y좌표, 폭, 높이, 넓이
# centroids : 각 레이블의 중심점 좌표

numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red)
# print(numOfLabels)
# print(img_label)
# print(stats)
# print(centroids)

for idx, centroid in enumerate(centroids) :
    if stats[idx][0] == 0 and stats[idx][1] == 0 :
        continue
    
    if np.any(np.isnan(centroid)) :
        continue
    
    x, y, w, h, area = stats[idx]
    # print(x, y, w, h, area)
    # print('-'*20)
    centerX, centerY = int(centroid[0]), int(centroid[1])

    # if area > 50 and abs(w-h) < 10 :
    if area > 150 and abs(w-h) < 5 : 
        # cv2.circle(img, (centerX, centerY), 10, (255, 0, 0), 2)
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

# cv2.imshow('res_blue', res_blue)
# cv2.imshow('res_green', res_green)
# cv2.imshow('res_yellow', res_yellow)
# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
# cv2.imshow('res_red', res_red)

cv2. imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [20]:
import cv2
import numpy as np
import matplotlib.pylab as plt


# 색상별 영역 지정
blue1 = np.array([90, 50, 50])
blue2 = np.array([120, 255, 255])

green1 = np.array([45, 50, 50])
green2 = np.array([75, 255, 255])

yellow1 = np.array([20, 50, 50])
yellow2 = np.array([35, 255, 255])

red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./sample3_515.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)
h, w = img.shape[:2]
# cv2. imshow('img', img)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)

img = cv2.bilateralFilter(img,9,105,105)
r,g,b=cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
# equalize=cv2.merge((r,g,b))
# cv2.imshow('equalize', equalize)
equalize=cv2.merge((r,g,b))

# 색상에 따른 마스크 생성
mask_blue = cv2.inRange(hsv, blue1, blue2)
mask_green = cv2.inRange(hsv, green1, green2)
mask_yellow = cv2.inRange(hsv, yellow1, yellow2)
mask_red1 = cv2.inRange(hsv, red1, red2)
cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

# kernel = np.ones((11, 11), np.uint8)
# mask_red1 = cv2.morphologyEx(mask_red1, cv2.MORPH_OPEN, kernel)
# mask_red1 = cv2.morphologyEx(mask_red1, cv2.MORPH_CLOSE, kernel)
# mask_red2 = cv2.morphologyEx(mask_red2, cv2.MORPH_OPEN, kernel)
# mask_red2 = cv2.morphologyEx(mask_red2, cv2.MORPH_CLOSE, kernel)

# 색상별 마스크로 색상만 추출
res_blue = cv2.bitwise_and(img, img, mask = mask_blue)
res_green = cv2.bitwise_and(img, img, mask = mask_green)
res_yellow = cv2.bitwise_and(img, img, mask = mask_yellow)

res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

# 연결 요소 레이블링
# : 연결된 요소들끼리 분리하는 방법
# : 바이너리 스케일 이미지에서 픽셀 값이 0으로 끊어지지 않는 영역끼리 같은 값을 부여해서 분리하는 방법
# retval, labels, stats, centroids 
#                 = cv2.connectedComponentsWithStats(src[, labels, stats, centroids, connectivity, ltype])
# retval : 레이블 개수
# labels : 레이블링된 입력 영상과 같은 크기의 배열
# src : 입력 영상, 바이너리 스케일 이미지
# stats : x좌표, y좌표, 폭, 높이, 넓이
# centroids : 각 레이블의 중심점 좌표

numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red2)
# print(numOfLabels)
# print(img_label)
# print(stats)
# print(centroids)

for idx, centroid in enumerate(centroids) :
    if stats[idx][0] == 0 and stats[idx][1] == 0 :
        continue
    
    if np.any(np.isnan(centroid)) :
        continue
    
    x, y, w, h, area = stats[idx]
    # print(x, y, w, h, area)
    # print('-'*20)
    centerX, centerY = int(centroid[0]), int(centroid[1])

    # if area > 50 and abs(w-h) < 10 :
    if area > 150 and abs(w-h) < 5 : 
        # cv2.circle(img, (centerX, centerY), 10, (255, 0, 0), 2)
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

# cv2.imshow('res_blue', res_blue)
# cv2.imshow('res_green', res_green)
# cv2.imshow('res_yellowa', res_yellow)
# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
# cv2.imshow('res_red', res_red)

cv2. imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [22]:
import cv2
import numpy as np
import matplotlib.pylab as plt


# 색상별 영역 지정
blue1 = np.array([90, 50, 50])
blue2 = np.array([120, 255, 255])

green1 = np.array([45, 50, 50])
green2 = np.array([75, 255, 255])

yellow1 = np.array([20, 50, 50])
yellow2 = np.array([35, 255, 255])

red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./frame1.PNG')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)
h, w = img.shape[:2]
# cv2. imshow('img', img)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)
# print(hsv)
img = cv2.bilateralFilter(img,9,105,105)
r,g,b=cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
# equalize=cv2.merge((r,g,b))
# cv2.imshow('equalize', equalize)
equalize=cv2.merge((r,g,b))

# 색상에 따른 마스크 생성
mask_blue = cv2.inRange(hsv, blue1, blue2)
mask_green = cv2.inRange(hsv, green1, green2)
mask_yellow = cv2.inRange(hsv, yellow1, yellow2)
mask_red1 = cv2.inRange(hsv, red1, red2)
cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

# kernel = np.ones((11, 11), np.uint8)
# mask_red1 = cv2.morphologyEx(mask_red1, cv2.MORPH_OPEN, kernel)
# mask_red1 = cv2.morphologyEx(mask_red1, cv2.MORPH_CLOSE, kernel)
# mask_red2 = cv2.morphologyEx(mask_red2, cv2.MORPH_OPEN, kernel)
# mask_red2 = cv2.morphologyEx(mask_red2, cv2.MORPH_CLOSE, kernel)

# 색상별 마스크로 색상만 추출
res_blue = cv2.bitwise_and(img, img, mask = mask_blue)
res_green = cv2.bitwise_and(img, img, mask = mask_green)
res_yellow = cv2.bitwise_and(img, img, mask = mask_yellow)

res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

# 연결 요소 레이블링
# : 연결된 요소들끼리 분리하는 방법
# : 바이너리 스케일 이미지에서 픽셀 값이 0으로 끊어지지 않는 영역끼리 같은 값을 부여해서 분리하는 방법
# retval, labels, stats, centroids 
#                 = cv2.connectedComponentsWithStats(src[, labels, stats, centroids, connectivity, ltype])
# retval : 레이블 개수
# labels : 레이블링된 입력 영상과 같은 크기의 배열
# src : 입력 영상, 바이너리 스케일 이미지
# stats : x좌표, y좌표, 폭, 높이, 넓이
# centroids : 각 레이블의 중심점 좌표

numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red2)
# print(numOfLabels)
# print(img_label)
# print(stats)
# print(centroids)

for idx, centroid in enumerate(centroids) :
    if stats[idx][0] == 0 and stats[idx][1] == 0 :
        continue
    
    if np.any(np.isnan(centroid)) :
        continue
    
    x, y, w, h, area = stats[idx]
    # print(x, y, w, h, area)
    # print('-'*20)
    centerX, centerY = int(centroid[0]), int(centroid[1])

    # if area > 50 and abs(w-h) < 10 :
    if area > 150 and abs(w-h) < 5 : 
        # cv2.circle(img, (centerX, centerY), 10, (255, 0, 0), 2)
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

# cv2.imshow('res_blue', res_blue)
# cv2.imshow('res_green', res_green)
# cv2.imshow('res_yellowa', res_yellow)
# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
# cv2.imshow('res_red', res_red)

cv2. imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [21]:
import cv2
import numpy as np
import matplotlib.pylab as plt


# 색상별 영역 지정
blue1 = np.array([90, 50, 50])
blue2 = np.array([120, 255, 255])

green1 = np.array([45, 50, 50])
green2 = np.array([75, 255, 255])

yellow1 = np.array([20, 50, 50])
yellow2 = np.array([35, 255, 255])

red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./sample3_515.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)
h, w = img.shape[:2]
# cv2. imshow('img', img)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)

img = cv2.bilateralFilter(img,9,105,105)
r,g,b=cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
# equalize=cv2.merge((r,g,b))
# cv2.imshow('equalize', equalize)
equalize=cv2.merge((r,g,b))

# 색상에 따른 마스크 생성
mask_blue = cv2.inRange(hsv, blue1, blue2)
mask_green = cv2.inRange(hsv, green1, green2)
mask_yellow = cv2.inRange(hsv, yellow1, yellow2)
mask_red1 = cv2.inRange(hsv, red1, red2)
cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

# kernel = np.ones((11, 11), np.uint8)
# mask_red1 = cv2.morphologyEx(mask_red1, cv2.MORPH_OPEN, kernel)
# mask_red1 = cv2.morphologyEx(mask_red1, cv2.MORPH_CLOSE, kernel)
# mask_red2 = cv2.morphologyEx(mask_red2, cv2.MORPH_OPEN, kernel)
# mask_red2 = cv2.morphologyEx(mask_red2, cv2.MORPH_CLOSE, kernel)

# 색상별 마스크로 색상만 추출
res_blue = cv2.bitwise_and(img, img, mask = mask_blue)
res_green = cv2.bitwise_and(img, img, mask = mask_green)
res_yellow = cv2.bitwise_and(img, img, mask = mask_yellow)

res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

# 연결 요소 레이블링
# : 연결된 요소들끼리 분리하는 방법
# : 바이너리 스케일 이미지에서 픽셀 값이 0으로 끊어지지 않는 영역끼리 같은 값을 부여해서 분리하는 방법
# retval, labels, stats, centroids 
#                 = cv2.connectedComponentsWithStats(src[, labels, stats, centroids, connectivity, ltype])
# retval : 레이블 개수
# labels : 레이블링된 입력 영상과 같은 크기의 배열
# src : 입력 영상, 바이너리 스케일 이미지
# stats : x좌표, y좌표, 폭, 높이, 넓이
# centroids : 각 레이블의 중심점 좌표

numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red2)
# print(numOfLabels)
# print(img_label)
# print(stats)
# print(centroids)

for idx, centroid in enumerate(centroids) :
    if stats[idx][0] == 0 and stats[idx][1] == 0 :
        continue
    
    if np.any(np.isnan(centroid)) :
        continue
    
    x, y, w, h, area = stats[idx]
    # print(x, y, w, h, area)
    # print('-'*20)
    centerX, centerY = int(centroid[0]), int(centroid[1])

    # if area > 50 and abs(w-h) < 10 :
    if area > 150 and abs(w-h) < 5 : 
        # cv2.circle(img, (centerX, centerY), 10, (255, 0, 0), 2)
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

# cv2.imshow('res_blue', res_blue)
# cv2.imshow('res_green', res_green)
# cv2.imshow('res_yellowa', res_yellow)
# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
# cv2.imshow('res_red', res_red)

cv2. imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
# https://yeowool0217.tistory.com/557
# 영상의 프레임을 가우시안 블러 처리 
# -> 필터 : GaussianBlur, medianBlur, bilateralFilter 테스트
# 블러된 프레임을 HSV로 변환
# HSV 범위에 있는 색만 추출
# 추출된 부분 에지 검출
# 관심 영역만 잘라내기
# 확률 허프 변환을 사용해 직선 찾기

In [ ]:
# 영상 획득
# 획득한 영상을 흑백 영상으로 변환
# 흑백영상을 이진화
# Edge 검출(cvCanny)
# 원 검출
# 검출한 원을 중심점 및 반지름을 구해서 Window에 표시

In [43]:
import cv2
import numpy as np

img_rgb = cv2.imread('./sample3_515.jpg') # 이미지 읽기
# print(image.shape) # (1080, 1920, 3)
img_rgb = cv2.resize(img_rgb, (img_rgb.shape[1]//2, img_rgb.shape[0]//2))
cv2.namedWindow("Original Image",cv2.WINDOW_NORMAL)

img = cv2.cvtColor(img_rgb,cv2.COLOR_RGB2HSV)
cv2.imshow("img1", img)

img = cv2.bilateralFilter(img,9,105,105)
cv2.imshow("img2", img)

r,g,b=cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
equalize=cv2.merge((r,g,b))
cv2.imshow("equalize1", equalize)
equalize = cv2.cvtColor(equalize,cv2.COLOR_RGB2GRAY)
cv2.imshow("equalize2", equalize)


ret,thresh_image = cv2.threshold(equalize,0,255,cv2.THRESH_OTSU+cv2.THRESH_BINARY)
cv2.imshow("thresh_image", thresh_image)
equalize= cv2.equalizeHist(thresh_image)
cv2.imshow("equalize3", equalize)


canny_image = cv2.Canny(equalize,250,255)
canny_image = cv2.convertScaleAbs(canny_image)
kernel = np.ones((3,3), np.uint8)
dilated_image = cv2.dilate(canny_image,kernel,iterations=1)

contours, hierarchy = cv2.findContours(dilated_image, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
contours= sorted(contours, key = cv2.contourArea, reverse = True)[:10]
c=contours[0]
print(cv2.contourArea(c))
final = cv2.drawContours(img, [c], -1, (255,0, 0), 3)

mask = np.zeros(img_rgb.shape,np.uint8)
new_image = cv2.drawContours(mask,[c],0,255,-1,)
new_image = cv2.bitwise_and(img_rgb, img_rgb, mask = equalize)

cv2.namedWindow("new",cv2.WINDOW_NORMAL)
cv2.imshow("new",new_image)

cv2.imshow("Original Image",img)
cv2.waitKey()
cv2.destroyAllWindows()

11917.5


In [42]:
# import numpy as np
# import cv2

# img1 = cv2.imread('./sample3_515.jpg')
# img2 = img1.copy()

# img2 = cv2.GaussianBlur(img2, (3, 3), 0)
# imgray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# circles = cv2.HoughCircles(imgray, cv2.HOUGH_GRADIENT, 1, 10, 
#                           param1 = 60, param2 = 50, minRadius = 0, maxRadius = 0)

# if circles is not None :
#     circles = np.uint16(np.around(circles))
    
#     for i in circles[0, :] :
#         cv2.circle(img1, (i[0], i[1]), i[2], (255, 255, 0), 1)
    
#     cv2.imshow('HoughCircles', img1)
#     cv2.waitKey()
#     cv2.destroyAllWindows()
# else :
#     print('No circle')

In [3]:
import cv2
import numpy as np
import matplotlib.pylab as plt


# 색상별 영역 지정
red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./sample3_515.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)
h, w = img.shape[:2]
# cv2. imshow('img', img)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)

img = cv2.bilateralFilter(img,9,105,105)
r,g,b=cv2.split(img)
equalize1= cv2.equalizeHist(r)
equalize2= cv2.equalizeHist(g)
equalize3= cv2.equalizeHist(b)
# equalize=cv2.merge((r,g,b))
# cv2.imshow('equalize', equalize)
equalize=cv2.merge((r,g,b))

# 색상에 따른 마스크 생성
mask_red1 = cv2.inRange(hsv, red1, red2)
# cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
# cv2.imshow('mask_red2', mask_red2)

mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

kernel = np.ones((11, 11), np.uint8)
mask_red1 = cv2.morphologyEx(mask_red1, cv2.MORPH_OPEN, kernel)
mask_red1 = cv2.morphologyEx(mask_red1, cv2.MORPH_CLOSE, kernel)
cv2.imshow('mask_red1', mask_red)
mask_red2 = cv2.morphologyEx(mask_red2, cv2.MORPH_OPEN, kernel)
mask_red2 = cv2.morphologyEx(mask_red2, cv2.MORPH_CLOSE, kernel)
cv2.imshow('mask_red2', mask_red)

# mask_red = mask_red1 + mask_red2
# cv2.imshow('mask_red', mask_red)

# 색상별 마스크로 색상만 추출
res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
cv2.imshow('res_red', res_red)

cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
mask_red.shape

(540, 960)

In [6]:
img1 = mask_red
# img1 = cv2.resize(img1, (img1.shape[1]//2, img1.shape[0]//2))

img2 = img1.copy()
cv2.imshow('img2', img2)
# img2 = cv2.GaussianBlur(img2, (3, 3), 0)
# img2 = cv2.bilateralFilter(img2, 9, 105, 105)

# imgray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

circles = cv2.HoughCircles(img2, cv2.HOUGH_GRADIENT, 1, 10, 
                          param1 = 60, param2 = 50, minRadius = 0, maxRadius = 0)

# print(circles[0][0])
if circles is not None :
    circles = np.uint16(np.around(circles))
    
    for i in circles[0, :] :
        cv2.circle(img1, (i[0], i[1]), i[2], (0, 0, 255), 10)
    
    cv2.imshow('HoughCircles', img1)
    cv2.waitKey()
    cv2.destroyAllWindows()
else :
    print('No circle')

cv2.waitKey()
cv2.destroyAllWindows()

No circle


In [9]:
img1 = mask_red
# img1 = cv2.resize(img1, (img1.shape[1]//2, img1.shape[0]//2))

img2 = img1.copy()
cv2.imshow('img2', img2)
img2 = cv2.GaussianBlur(img2, (3, 3), 0)
# img2 = cv2.bilateralFilter(img2, 9, 105, 105)

# imgray = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

circles = cv2.HoughCircles(img2, cv2.HOUGH_GRADIENT, 1, 10, 
                          param1 = 60, param2 = 50, minRadius = 0, maxRadius = 0)

centroids, labels = cv2.connectedComponents(img2)

for i in range(centroids) :
    img2[labels == i] = [int(j) for j in np.random.randint(0, 255, 3)]

# print(circles[0][0])
if circles is not None :
    circles = np.uint16(np.around(circles))
    
    for i in circles[0, :] :
        cv2.circle(img1, (i[0], i[1]), i[2], (0, 255, 255), 10)
    
    cv2.imshow('HoughCircles', img1)
    cv2.waitKey()
    cv2.destroyAllWindows()
else :
    print('No circle')

cv2.imshow('final1', img1)
cv2.imshow('final2', img2)

cv2.waitKey()
cv2.destroyAllWindows()

ValueError: NumPy boolean array indexing assignment cannot assign 3 input values to the 480481 output values where the mask is true