In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [14]:
img = cv2.imread('./sample1.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))
img_yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)

cv2.imshow('img', img)
cv2.imshow('img_yuv', img_yuv)

# cv2.imshow('img_yuv[:, :, 0]', img_yuv[:, :, 0])
# cv2.imshow('img_yuv[:, :, 1]', img_yuv[:, :, 1])
# cv2.imshow('img_yuv[:, :, 2]', img_yuv[:, :, 2])
img2 = img_yuv[:, :, 2]
print(img2)
# thr, mask1 = cv2.threshold(img2, 127, 1, cv2.THRESH_BINARY)
# print(thr)
# cv2.imshow('mask1', mask1)

# thr, mask2 = cv2.threshold(img2, 127, 1, cv2.THRESH_BINARY_INV)
# cv2.imshow('mask2', mask2)

thr, mask3 = cv2.threshold(img2, 127, 255, cv2.THRESH_BINARY)
cv2.imshow('mask3', mask3)

t, t_otsu = cv2.threshold(img2, -1, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
cv2.imshow('t_otsu', t_otsu)
print(t)
# adapt_mask = cv2.adaptiveThreshold(img2, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 11, 10)
# cv2.imshow('adapt_mask', adapt_mask)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[117 117 117 ... 123 123 123]
 [117 117 117 ... 123 123 123]
 [117 117 117 ... 123 123 123]
 ...
 [127 127 127 ... 122 122 122]
 [127 127 127 ... 121 121 121]
 [127 127 127 ... 121 121 121]]
125.0


In [16]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('./sample1.jpg')[:, :, 0]

img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))
cv2.imshow('img', img)

thr, mask3 = cv2.threshold(img, 200, 255, cv2.THRESH_BINARY_INV)
cv2.imshow('mask3', mask3)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('./sample1.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))
img_yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)

# cv2.imshow('img', img)
# cv2.imshow('img_yuv', img_yuv)
img2 = img_yuv[:, :, 2]
# cv2.imshow('img2', img2)
# print(img2)

img3 = img_yuv[:, :, 0]
cv2.imshow('img3', img3)
# print(img2)

# 필터 커널 세팅
kernel = np.ones((1, 1), np.uint8)
kernel2 = np.ones((4, 4), np.uint8)

thr, mask3 = cv2.threshold(img2, 200, 255, cv2.THRESH_BINARY)
cv2.imshow('mask3', mask3)
erosion_image = cv2.erode(mask3, kernel, iterations=1)  
dilation_image = cv2.dilate(erosion_image, kernel2, iterations=1) 
cv2.imshow('dilation_image', dilation_image)

# 블록 사이즈
blk_size = 9
# 차감 상수
C = 5

# 오츠의 알고리즘으로 단일 경계값을 전체 이미지에 적용
# ret, th1 = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

# 적응형 스레시홀드를 평균과 가우시안 분포로 각각 적용
# th2 = cv2.adaptiveThreshold(img2, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, blk_size, C)
# th3 = cv2.adaptiveThreshold(img2, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, blk_size, C)
# cv2.imshow('th2', th2)
# cv2.imshow('th3', th3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [64]:
img = cv2.imread('./color.PNG')

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV )

# print(hsv[0][np.argmax(hsv[0], axis = 0)])
# print(hsv[0][np.argmin(hsv[0], axis = 0)])
# print(hsv[1][np.argmax(hsv[1], axis = 0)])
# print(hsv[1][np.argmin(hsv[1], axis = 0)])
# print(hsv[2][np.argmax(hsv[2], axis = 0)])
# print(hsv[2][np.argmin(hsv[2], axis = 0)])
cv2.imshow('hsv', hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\imgproc\src\thresh.cpp:1645: error: (-215:Assertion failed) src.type() == CV_8UC1 in function 'cv::adaptiveThreshold'


In [2]:
# 필터 커널 세팅
kernel = np.ones((1, 1), np.uint8)
kernel2 = np.ones((3, 3), np.uint8)

# 필터 
red1 = np.array([0, 50, 0]) # 밝은 빨강(주황계열)
red2 = np.array([5, 250, 240])

# Hue : 0~180
# Saturation : 0~255
# Value : 0~255

red3 = np.array([165, 50, 0]) # 어두운 빨강(갈색계열)
red4 = np.array([175, 250, 240])

In [16]:
# red1 = np.array([0, 30, 100]) # 밝은 빨강(주황계열)
# red2 = np.array([5, 150, 200])

# red3 = np.array([155, 30, 100]) # 어두운 빨강(갈색계열)
# red4 = np.array([180, 150, 200])

In [20]:
red1 = np.array([0, 30, 0]) # 밝은 빨강(주황계열)
red2 = np.array([5, 250, 240])

red3 = np.array([155, 50, 0]) # 어두운 빨강(갈색계열)
red4 = np.array([180, 250, 240])

In [32]:
img = cv2.imread('./frame1.PNG')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [41]:
# (388, 836, 3)
roi = img[0:int(img.shape[0]*0.8), :, 2]

In [42]:
cv2.imshow('roi', roi)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
kernel = np.ones((1, 1), np.uint8)
kernel2 = np.ones((4, 4), np.uint8)

In [5]:
# 영상 경로 설정
video_path= './video1.mp4'
cap = cv2.VideoCapture(video_path)

# 영상 이름
video_file = video_path.split('/')[-1]
video_name = video_file.split('.')[0]

while True :
    # 영상 읽기
    ret, img = cap.read()
    
    # 마지막 프레임 확인
    if ret is None:
        break
        
    img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))
    # roi = img[0:int(img.shape[0]*0.8), :, :]
    # blur = cv2.GaussianBlur( img, (3,3), 0 )    
    # hsv = cv2.cvtColor( blur, cv2.COLOR_BGR2HSV )
    
    # 색상에 따른 마스크 생성
    # mask_red1 = cv2.inRange(hsv, red1, red2)
    # mask_red2 = cv2.inRange(hsv, red3, red4)
    
    # 마스크 결합
    # mask_red = mask_red1 + mask_red2
    # thr, mask_red = cv2.threshold(mask_red, 235, 1, cv2.THRESH_BINARY)

    # mask_red = cv2.adaptiveThreshold(mask_red, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 11, 10)

    
    yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
    img2 = yuv[:, :, 2]

    thr, mask_red = cv2.threshold(img2, 150, 255, cv2.THRESH_BINARY)
    
    # 침식 (노이즈제거) -> 팽창(픽셀 살리기)
    erosion_mask = cv2.erode(mask_red, kernel, iterations=1)
    # cv2.imshow('erosion_mask', erosion_mask)
    dilation_mask = cv2.dilate(erosion_mask, kernel2, iterations=1) 
    # cv2.imshow('dilation_mask', dilation_mask)
    
    contours, hierarchy = cv2.findContours(dilation_mask, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

    mask_external = np.zeros(dilation_mask.shape, dilation_mask.dtype)
    for i in range(len(contours)) :
        if hierarchy[0][i][3] == -1 :
            cv2.drawContours(mask_external, contours, i, 255, -1)

        
    mask_internal = np.zeros(dilation_mask.shape, dilation_mask.dtype)
    for i in range(len(contours)) :
        if hierarchy[0][i][3] != -1 :
            cv2.drawContours(mask_internal, contours, i, 255, -1)
                    
    _, _, stats_i, centroids_i = cv2.connectedComponentsWithStats(mask_internal)
    _, _, stats_e, centroids_e = cv2.connectedComponentsWithStats(mask_external)
    
    for idx, centroid in enumerate(centroids) :
        
        if stats[idx][0] == 0 and stats[idx][1] == 0 :
            continue
        if np.any(np.isnan(centroid)) :
            continue

        x, y, w, h, area = stats[idx]
        centerX, centerY = int(centroid[0]), int(centroid[1])

        if area > 120 and abs(w-h) < 5 :
            # cv2.rectangle(img, (x-10, y-10), (x+w+10, y+h+10), (0, 0, 255), 2)
            # cv2.circle(img, ( centerX, centerY ), 2, (0, 255, 0), 2)
            # print(x, y, w, h, area)

#             detected_img = img[y-10 : y+h+10,  x-10 : x+w+10]
#             gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
#             circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=200, param2=30, minRadius=0, maxRadius=0)
#             if circles is not None :
#                 circles = np.uint16(np.around(circles))

#                 for i in circles[0, :] :
#                     cv2.circle(img, ( centerX, centerY ), 2, (0, 255, 0), 2)
#                     cv2.rectangle(img, (x-10, y-10), (x+w+10, y+h+10), (0, 0, 255), 2)
                
            try : 
                detected_img = img[y-10 : y+h+10,  x-10 : x+w+10]
                gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
                circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=100, param2=30)
                if circles is not None :
                    circles = np.uint16(np.around(circles))

                    for i in circles[0, :] :
                        cv2.circle(img, ( centerX, centerY ), 2, (0, 255, 0), 2)
                        cv2.rectangle(img, (x-10, y-10), (x+w+10, y+h+10), (0, 0, 255), 2)
            except : 
                continue

    cv2.imshow('img', img)
    cv2.imshow('mask_internal', mask_internal)

    if cv2.waitKey(1) == 27 :
        cap.release()
        cv2.destroyAllWindows()

cv2.waitKey(0)
cap.release()
cv2.destroyAllWindows()

AttributeError: 'NoneType' object has no attribute 'shape'

In [10]:
# 영상 경로 설정
video_path= './video10.mp4'
cap = cv2.VideoCapture(video_path)

# 영상 이름
video_file = video_path.split('/')[-1]
video_name = video_file.split('.')[0]

while True :
    # 영상 읽기
    ret, img = cap.read()
    
    # 마지막 프레임 확인
    if ret is None:
        break
        
    img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))
    # roi = img[0:int(img.shape[0]*0.8), :, :]
    # blur = cv2.GaussianBlur( img, (3,3), 0 )    
    # hsv = cv2.cvtColor( blur, cv2.COLOR_BGR2HSV )
    
    # 색상에 따른 마스크 생성
    # mask_red1 = cv2.inRange(hsv, red1, red2)
    # mask_red2 = cv2.inRange(hsv, red3, red4)
    
    # 마스크 결합
    # mask_red = mask_red1 + mask_red2
    # thr, mask_red = cv2.threshold(mask_red, 235, 1, cv2.THRESH_BINARY)

    # mask_red = cv2.adaptiveThreshold(mask_red, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 11, 10)

    
    yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
    img2 = yuv[:, :, 2]

    thr, mask_red = cv2.threshold(img2, 150, 255, cv2.THRESH_BINARY)
    
    # 침식 (노이즈제거) -> 팽창(픽셀 살리기)
    erosion_mask = cv2.erode(mask_red, kernel, iterations=1)
    # cv2.imshow('erosion_mask', erosion_mask)
    dilation_mask = cv2.dilate(erosion_mask, kernel2, iterations=1) 
    # cv2.imshow('dilation_mask', dilation_mask)
    
    contours, hierarchy = cv2.findContours(dilation_mask, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

    mask_external = np.zeros(dilation_mask.shape, dilation_mask.dtype)
    for i in range(len(contours)) :
        if hierarchy[0][i][3] == -1 :
            cv2.drawContours(mask_external, contours, i, 255, -1)

        
    mask_internal = np.zeros(dilation_mask.shape, dilation_mask.dtype)
    for i in range(len(contours)) :
        if hierarchy[0][i][3] != -1 :
            cv2.drawContours(mask_internal, contours, i, 255, -1)
                    
    _, _, stats_i, centroids_i = cv2.connectedComponentsWithStats(mask_internal)
    _, _, stats_e, centroids_e = cv2.connectedComponentsWithStats(mask_external)
    
    for idx, centroid_i in enumerate(centroids_i) :
        
        if stats_i[idx][0] == 0 and stats_i[idx][1] == 0 :
            continue
        if np.any(np.isnan(centroid_i)) :
            continue
            
        for centroid_e in centroids_e :
            if abs(centroid_i[0] - centroid_e[0]) < 3 and abs(centroid_i[1] - centroid_e[1]) < 3 :
                x, y, w, h, area = stats_i[idx]
                centerX, centerY = int(centroid_i[0]), int(centroid_i[1])

                if area > 120 and abs(w-h) < 5 :
            # cv2.rectangle(img, (x-10, y-10), (x+w+10, y+h+10), (0, 0, 255), 2)
            # cv2.circle(img, ( centerX, centerY ), 2, (0, 255, 0), 2)
            # print(x, y, w, h, area)

#             detected_img = img[y-10 : y+h+10,  x-10 : x+w+10]
#             gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
#             circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=200, param2=30, minRadius=0, maxRadius=0)
#             if circles is not None :
#                 circles = np.uint16(np.around(circles))

#                 for i in circles[0, :] :
#                     cv2.circle(img, ( centerX, centerY ), 2, (0, 255, 0), 2)
#                     cv2.rectangle(img, (x-10, y-10), (x+w+10, y+h+10), (0, 0, 255), 2)
                
                    try : 
                        detected_img = img[y-10 : y+h+10,  x-10 : x+w+10]
                        gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
                        circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=100, param2=30)
                        if circles is not None :
                            circles = np.uint16(np.around(circles))

                            for i in circles[0, :] :
                                cv2.circle(img, ( centerX, centerY ), 2, (0, 255, 0), 2)
                                cv2.rectangle(img, (x-10, y-10), (x+w+10, y+h+10), (0, 0, 255), 2)
                    except : 
                        continue

    cv2.imshow('img', img)
#     cv2.imshow('mask_internal', mask_internal)
#     cv2.imshow('mask_external', mask_external)
    if cv2.waitKey(1) == 27 :
        cap.release()
        cv2.destroyAllWindows()

cv2.waitKey(0)
cap.release()
cv2.destroyAllWindows()

AttributeError: 'NoneType' object has no attribute 'shape'

In [23]:
############################################################################################################
    # 마지막 코드 #
############################################################################################################

# 영상 경로 설정
video_path= './video1.mp4'
cap = cv2.VideoCapture(video_path)

# 영상 이름
video_file = video_path.split('/')[-1]
video_name = video_file.split('.')[0]

while True :
    # 영상 읽기
    ret, img = cap.read()
    
    # 마지막 프레임 확인
    if ret is None:
        break
        
    img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))    
    yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
    img2 = yuv[:, :, 2]

    thr, mask_red = cv2.threshold(img2, 140, 255, cv2.THRESH_BINARY)
    
    # 침식 (노이즈제거) -> 팽창(픽셀 살리기)
    erosion_mask = cv2.erode(mask_red, kernel, iterations=1)
    dilation_mask = cv2.dilate(erosion_mask, kernel2, iterations=1) 
    
    contours, hierarchy = cv2.findContours(dilation_mask, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

    mask_external = np.zeros(dilation_mask.shape, dilation_mask.dtype)
    for i in range(len(contours)) :
        if hierarchy[0][i][3] == -1 :
            cv2.drawContours(mask_external, contours, i, 255, -1)

    mask_internal = np.zeros(dilation_mask.shape, dilation_mask.dtype)
    for i in range(len(contours)) :
        if hierarchy[0][i][3] != -1 :
            cv2.drawContours(mask_internal, contours, i, 255, -1)
                    
    _, _, stats_i, centroids_i = cv2.connectedComponentsWithStats(mask_internal)
    _, _, stats_e, centroids_e = cv2.connectedComponentsWithStats(mask_external)
    
    for idx, centroid_i in enumerate(centroids_i) :
        
        if stats_i[idx][0] == 0 and stats_i[idx][1] == 0 :
            continue
        if np.any(np.isnan(centroid_i)) :
            continue
            
        for centroid_e in centroids_e :
            if abs(centroid_i[0] - centroid_e[0]) < 3 and abs(centroid_i[1] - centroid_e[1]) < 3 :
                x, y, w, h, area = stats_i[idx]
                centerX, centerY = int(centroid_i[0]), int(centroid_i[1])

                if area > 120 and abs(w-h) < 5 :
                    try : 
                        detected_img = img[y-10 : y+h+10,  x-10 : x+w+10]
                        gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
                        circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=100, param2=30)
                        if circles is not None :
                            circles = np.uint16(np.around(circles))

                            for i in circles[0, :] :
                                cv2.circle(img, ( centerX, centerY ), 2, (0, 255, 0), 2)
                                cv2.rectangle(img, (x-10, y-10), (x+w+10, y+h+10), (0, 0, 255), 2)
                    except : 
                        continue

    cv2.imshow('img', img)
    if cv2.waitKey(1) == 27 :
        cap.release()
        cv2.destroyAllWindows()

cv2.waitKey(0)
cap.release()
cv2.destroyAllWindows()

AttributeError: 'NoneType' object has no attribute 'shape'

In [16]:

# 영상 경로 설정
video_path= './video1.mp4'
cap = cv2.VideoCapture(video_path)

# 영상 이름
video_file = video_path.split('/')[-1]
video_name = video_file.split('.')[0]

while True :
    # 영상 읽기
    ret, img = cap.read()
    
    # 마지막 프레임 확인
    if ret is None:
        break
        
    img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))
    blur = cv2.GaussianBlur( img, (3,3), 0 )    
    hsv = cv2.cvtColor( blur, cv2.COLOR_BGR2HSV )
    
    # 색상에 따른 마스크 생성
    mask_red1 = cv2.inRange(hsv, red1, red2)
    mask_red2 = cv2.inRange(hsv, red3, red4)
    
    # 마스크 결합
    mask_red = mask_red1 + mask_red2
    
    # 침식 (노이즈제거) -> 팽창(픽셀 살리기)
    erosion_mask = cv2.erode(mask_red, kernel, iterations=1)
    # cv2.imshow('erosion_mask', erosion_mask)
    dilation_mask = cv2.dilate(erosion_mask, kernel2, iterations=1) 
    # cv2.imshow('dilation_mask', dilation_mask)
    
    contours, hierarchy = cv2.findContours(dilation_mask, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

    mask_internal = np.zeros(dilation_mask.shape, dilation_mask.dtype)
    for i in range(len(contours)) :
        if hierarchy[0][i][3] != -1 :
            cv2.drawContours(mask_internal, contours, i, 255, -1)
            
    numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_internal)
    
    for idx, centroid in enumerate(centroids) :
        
        if stats[idx][0] == 0 and stats[idx][1] == 0 :
            continue
        if np.any(np.isnan(centroid)) :
            continue

        x, y, w, h, area = stats[idx]
        centerX, centerY = int(centroid[0]), int(centroid[1])

        if area > 120 and abs(w-h) < 5 :
            # cv2.rectangle(img, (x-10, y-10), (x+w+10, y+h+10), (0, 0, 255), 2)
            # cv2.circle(img, ( centerX, centerY ), 2, (0, 255, 0), 2)
            # print(x, y, w, h, area)

#             detected_img = img[y-10 : y+h+10,  x-10 : x+w+10]
#             gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
#             circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=200, param2=30, minRadius=0, maxRadius=0)
#             if circles is not None :
#                 circles = np.uint16(np.around(circles))

#                 for i in circles[0, :] :
#                     cv2.circle(img, ( centerX, centerY ), 2, (0, 255, 0), 2)
#                     cv2.rectangle(img, (x-10, y-10), (x+w+10, y+h+10), (0, 0, 255), 2)
                
            try : 
                detected_img = img[y-10 : y+h+10,  x-10 : x+w+10]
                gray_detected_img = cv2.cvtColor(detected_img, cv2.COLOR_BGR2GRAY)
                circles = cv2.HoughCircles(gray_detected_img, cv2.HOUGH_GRADIENT, 1, 100, param1=100, param2=30)
                if circles is not None :
                    circles = np.uint16(np.around(circles))

                    for i in circles[0, :] :
                        cv2.circle(img, ( centerX, centerY ), 2, (0, 255, 0), 2)
                        cv2.rectangle(img, (x-10, y-10), (x+w+10, y+h+10), (0, 0, 255), 2)
            except : 
                continue

    cv2.imshow('img', img)
    cv2.imshow('mask_internal', mask_internal)

    if cv2.waitKey(1) == 27 :
        cap.release()
        cv2.destroyAllWindows()

cv2.waitKey(0)
cap.release()
cv2.destroyAllWindows()

NameError: name 'red1' is not defined