In [ ]:
# [방법 1]
# https://cccding.tistory.com/110
# opencv을 이용한 자율주행 자동차

# 1. PC에서 Opencv를 이용한 차선, 정지선 인식
# - HoughLinesP 함수와 기울기를 이용한 알고리즘을 통해 직선 및 커브 검출

# 2. 라즈베리파이에서 Opencv를 이용한 표지판, 신호등 인식
# - 전처리 과정을 거친 후 원검출과 색검출을 이용하였고 
# Template matching을 사용하여 속도를 인식

# 3. Atmega128에서 dc 및 servo 모터 구동 및 장애물 인식
# - PWN을 이용해 모터 제어 및 초음파 센서를 이용하여 장애물 탐지

In [ ]:
# [방법 2]
# https://arclab.tistory.com/205

In [ ]:
# [방법 3]
# https://github.com/aarcosg/traffic-sign-detection

In [ ]:
# [방법 4]
# https://webnautes.tistory.com/1246

In [ ]:
import cv2
import numpy as np

img = cv2.imread('./sample3_515.jpg')
print(img.shape)

(1080, 1920, 3)


In [ ]:
import cv2
import numpy as np

img = cv2.imread('./sample3_515.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

cv2.imshow('BGR2HSV', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
import matplotlib.pylab as plt

img = cv2.imread('./sample3_515.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2))
cv2. imshow('img', img)
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
cv2. imshow('hsv', hsv)

cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np
import matplotlib.pylab as plt

img = cv2.imread('./sample3_515.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)
cv2. imshow('img', img)
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)

# 색상별 영역 지정
blue1 = np.array([90, 50, 50])
blue2 = np.array([120, 255, 255])

green1 = np.array([45, 50, 50])
green2 = np.array([75, 255, 255])

yellow1 = np.array([20, 50, 50])
yellow2 = np.array([35, 255, 255])

red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

# 색상에 따른 마스크 생성
mask_blue = cv2.inRange(hsv, blue1, blue2)
mask_green = cv2.inRange(hsv, green1, green2)
mask_yellow = cv2.inRange(hsv, yellow1, yellow2)
mask_red1 = cv2.inRange(hsv, red1, red2)
# cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
# cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

# 색상별 마스크로 색상만 추출
res_blue = cv2.bitwise_and(img, img, mask = mask_blue)
res_green = cv2.bitwise_and(img, img, mask = mask_green)
res_yellow = cv2.bitwise_and(img, img, mask = mask_yellow)

res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

# cv2.imshow('res_blue', res_blue)
# cv2.imshow('res_green', res_green)
# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
# cv2.imshow('res_red', res_red)
# cv2.imshow('res_yellow', res_yellow)

# kernel = np.ones((11, 11), np.uint8)
# img_mask = cv2.morphologyEx(img_mask, cv2.MORPH_OPEN, kernel)
# img_mask = cv2.morphologyEx(img_mask, cv2.MORPH_CLOSE, kernel)

img = cv2.imread('./sample3_515.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)
h, w = img.shape[:2]
cv2. imshow('img', img)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)



cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
import cv2
import numpy as np
import matplotlib.pylab as plt


# 색상별 영역 지정
blue1 = np.array([90, 50, 50])
blue2 = np.array([120, 255, 255])

green1 = np.array([45, 50, 50])
green2 = np.array([75, 255, 255])

yellow1 = np.array([20, 50, 50])
yellow2 = np.array([35, 255, 255])

red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./sample3_515.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)
h, w = img.shape[:2]
# cv2. imshow('img', img)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)

# 색상에 따른 마스크 생성
mask_blue = cv2.inRange(hsv, blue1, blue2)
mask_green = cv2.inRange(hsv, green1, green2)
mask_yellow = cv2.inRange(hsv, yellow1, yellow2)
mask_red1 = cv2.inRange(hsv, red1, red2)
# cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
# cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

kernel = np.ones((11, 11), np.uint8)
mask_red = cv2.morphologyEx(mask_red, cv2.MORPH_OPEN, kernel)
mask_red = cv2.morphologyEx(mask_red, cv2.MORPH_CLOSE, kernel)

# 색상별 마스크로 색상만 추출
res_blue = cv2.bitwise_and(img, img, mask = mask_blue)
res_green = cv2.bitwise_and(img, img, mask = mask_green)
res_yellow = cv2.bitwise_and(img, img, mask = mask_yellow)

res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

# 연결 요소 레이블링
# : 연결된 요소들끼리 분리하는 방법
# : 바이너리 스케일 이미지에서 픽셀 값이 0으로 끊어지지 않는 영역끼리 같은 값을 부여해서 분리하는 방법
# retval, labels, stats, centroids 
#                 = cv2.connectedComponentsWithStats(src[, labels, stats, centroids, connectivity, ltype])
# retval : 레이블 개수
# labels : 레이블링된 입력 영상과 같은 크기의 배열
# src : 입력 영상, 바이너리 스케일 이미지
# stats : x좌표, y좌표, 폭, 높이, 넓이
# centroids : 각 레이블의 중심점 좌표

numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red)
print(numOfLabels)
print(img_label)
print(stats)
print(centroids)

for idx, centroid in enumerate(centroids) :
    if stats[idx][0] == 0 and stats[idx][1] == 0 :
        continue
    
    if np.any(np.isnan(centroid)) :
        continue
    
    x, y, w, h, area = stats[idx]
    centerX, centerY = int(centroid[0]), int(centroid[1])

    if area > 50 :
        cv2.circle(img, (centerX, centerY), 10, (0, 0, 255), 10)
        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 255))

# cv2.imshow('res_blue', res_blue)
# cv2.imshow('res_green', res_green)
# cv2.imshow('res_yellow', res_yellow)
# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
cv2.imshow('res_red', res_red)

cv2. imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

9
[[0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 [0 0 0 ... 3 3 3]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[     0      0    960    540 499712]
 [   721      0     51    115   2716]
 [   780      0     15     13    188]
 [   896      0     64    141   6955]
 [   740    151     74    255   7960]
 [   688    292     12     12    143]
 [   408    323     22     11    242]
 [   492    324     21     12    248]
 [   102    348     15     16    236]]
[[467.10176262 272.97623631]
 [751.71502209  66.55081001]
 [786.7393617    5.88829787]
 [930.4813803   60.90208483]
 [771.9491206  302.30025126]
 [693.46153846 297.53846154]
 [418.5        328.        ]
 [502.06854839 329.45564516]
 [108.94491525 355.62288136]]


In [6]:
import cv2
import numpy as np
import matplotlib.pylab as plt


# 색상별 영역 지정
blue1 = np.array([90, 50, 50])
blue2 = np.array([120, 255, 255])

green1 = np.array([45, 50, 50])
green2 = np.array([75, 255, 255])

yellow1 = np.array([20, 50, 50])
yellow2 = np.array([35, 255, 255])

red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

img = cv2.imread('./sample3_515.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)
h, w = img.shape[:2]
# cv2. imshow('img', img)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)

# 색상에 따른 마스크 생성
mask_blue = cv2.inRange(hsv, blue1, blue2)
mask_green = cv2.inRange(hsv, green1, green2)
mask_yellow = cv2.inRange(hsv, yellow1, yellow2)
mask_red1 = cv2.inRange(hsv, red1, red2)
# cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
# cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
cv2.imshow('mask_red', mask_red)

kernel = np.ones((11, 11), np.uint8)
mask_red = cv2.morphologyEx(mask_red, cv2.MORPH_OPEN, kernel)
mask_red = cv2.morphologyEx(mask_red, cv2.MORPH_CLOSE, kernel)

# 색상별 마스크로 색상만 추출
res_blue = cv2.bitwise_and(img, img, mask = mask_blue)
res_green = cv2.bitwise_and(img, img, mask = mask_green)
res_yellow = cv2.bitwise_and(img, img, mask = mask_yellow)

res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

# 연결 요소 레이블링
# : 연결된 요소들끼리 분리하는 방법
# : 바이너리 스케일 이미지에서 픽셀 값이 0으로 끊어지지 않는 영역끼리 같은 값을 부여해서 분리하는 방법
# retval, labels, stats, centroids 
#                 = cv2.connectedComponentsWithStats(src[, labels, stats, centroids, connectivity, ltype])
# retval : 레이블 개수
# labels : 레이블링된 입력 영상과 같은 크기의 배열
# src : 입력 영상, 바이너리 스케일 이미지
# stats : x좌표, y좌표, 폭, 높이, 넓이
# centroids : 각 레이블의 중심점 좌표

img2 = np.zeros_like(img)

centroids, labels = cv2.connectedComponents(mask_red)

for i in range(centroids) :
    img2[labels == i] = [int(j) for j in np.random.randint(0, 255, 3)]

# numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red)
# print(numOfLabels)
# print(img_label)
# print(stats)
# print(centroids)

# for idx, centroid in enumerate(centroids) :
#     if stats[idx][0] == 0 and stats[idx][1] == 0 :
#         continue
    
#     if np.any(np.isnan(centroid)) :
#         continue
    
#     x, y, w, h, area = stats[idx]
#     centerX, centerY = int(centroid[0]), int(centroid[1])

#     if area > 50 :
#         cv2.circle(img, (centerX, centerY), 10, (0, 0, 255), 10)
#         cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 255))

# cv2.imshow('res_blue', res_blue)
# cv2.imshow('res_green', res_green)
# cv2.imshow('res_yellow', res_yellow)
# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
cv2.imshow('res_red', res_red)

cv2. imshow('img', img)
cv2. imshow('img2', img2)

cv2.waitKey()
cv2.destroyAllWindows()

In [1]:
import cv2 # opencv 사용
import numpy as np


image = cv2.imread('./sample3_515.jpg')
image = cv2.resize(image, (image.shape[1]//2, image.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)

mark = np.copy(image) # image 복사

#  BGR 제한 값 설정
blue_threshold = 205
green_threshold = 205
red_threshold = 205
bgr_threshold = [blue_threshold, green_threshold, red_threshold]

# BGR 제한 값보다 작으면 검은색으로
thresholds = (image[:,:,0] < bgr_threshold[0]) | (image[:,:,1] < bgr_threshold[1]) | (image[:,:,2] < bgr_threshold[2])
mark[thresholds] = [0,0,0]

cv2.imshow('white',mark) # 흰색 추출 이미지 출력
cv2.imshow('result',image) # 이미지 출력
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [11]:
# 흰색 검출
import numpy as np
import cv2

color = [255, 255, 255]
pixel = np.uint8([[color]])

hsv = cv2.cvtColor(pixel, cv2.COLOR_BGR2HSV)
hsv = hsv[0][0]

print("bgr : ", color)
print("hsv : ", hsv)

bgr :  [255, 255, 255]
hsv :  [  0   0 255]


In [27]:
# 흰색 검출
import numpy as np
import cv2

color = [180, 180 ,180]
pixel = np.uint8([[color]])

hsv = cv2.cvtColor(pixel, cv2.COLOR_BGR2HSV)
hsv = hsv[0][0]

print("bgr : ", color)
print("hsv : ", hsv)

bgr :  [180, 180, 180]
hsv :  [  0   0 180]


In [30]:
# 흰색 검출
import numpy as np
import cv2

color = [200, 200, 200]
pixel = np.uint8([[color]])

hsv = cv2.cvtColor(pixel, cv2.COLOR_BGR2HSV)
hsv = hsv[0][0]

print("bgr : ", color)
print("hsv : ", hsv)

bgr :  [200, 200, 200]
hsv :  [  0   0 200]


In [8]:
print(blue1)

[90 50 50]


In [9]:
white = np.array([0, 0, 255])

In [10]:
print(white)

[  0   0 255]


In [7]:
mask_blue

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [255,   0,   0, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ..., 255, 255, 255],
       [  0,   0,   0, ..., 255, 255, 255]], dtype=uint8)

In [5]:
import cv2
import numpy as np
import matplotlib.pylab as plt


# 색상별 영역 지정
blue1 = np.array([90, 50, 50])
blue2 = np.array([120, 255, 255])

green1 = np.array([45, 50, 50])
green2 = np.array([75, 255, 255])

yellow1 = np.array([20, 50, 50])
yellow2 = np.array([35, 255, 255])

red1 = np.array([0, 50, 50])
red2 = np.array([15, 255, 255])
red3 = np.array([165, 50, 50])
red4 = np.array([180, 255, 255])

# white = np.array([0, 0, 255])

img = cv2.imread('./sample3_515.jpg')
img = cv2.resize(img, (img.shape[1]//2, img.shape[0]//2), 
                 interpolation = cv2.INTER_AREA)
h, w = img.shape[:2]
cv2. imshow('img', img)

# HSV 영상으로 변환
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# cv2. imshow('hsv', hsv)

# 색상에 따른 마스크 생성
mask_blue = cv2.inRange(hsv, blue1, blue2)
# cv2.imshow('mask_blue', mask_blue)
mask_green = cv2.inRange(hsv, green1, green2)
# cv2.imshow('mask_green', mask_green)
mask_yellow = cv2.inRange(hsv, yellow1, yellow2)
mask_red1 = cv2.inRange(hsv, red1, red2)
# cv2.imshow('mask_red1', mask_red1)
mask_red2 = cv2.inRange(hsv, red3, red4)
# cv2.imshow('mask_red2', mask_red2)
mask_red = mask_red1 + mask_red2
# cv2.imshow('mask_red', mask_red)

# for white
# cvInRangeS(imgHSV, cvScalar(0, 0, 200, 0), cvScalar(180, 255, 255, 0), imgThreshold);
# lower_white = np.array([0, 0, 230])
# upper_white = np.array([180, 25, 255])
mask_white = cv2.inRange(hsv, np.array([0, 0, 0]), np.array([0, 0, 255]))
# sensitivity = 15
# lower_white = np.array([0, 0, 255-sensitivity])
# upper_white = np.array([180, sensitivity, 255])
# mask_white = cv2.inRange(hsv, lower_white, upper_white)

cv2.imshow('mask_white', mask_white)

kernel = np.ones((11, 11), np.uint8)
mask_white = cv2.morphologyEx(mask_white, cv2.MORPH_OPEN, kernel)
mask_white = cv2.morphologyEx(mask_white, cv2.MORPH_CLOSE, kernel)

# 색상별 마스크로 색상만 추출
res_blue = cv2.bitwise_and(img, img, mask = mask_blue)
res_green = cv2.bitwise_and(img, img, mask = mask_green)
res_yellow = cv2.bitwise_and(img, img, mask = mask_yellow)

res_red1 = cv2.bitwise_and(img, img, mask = mask_red1)
# cv2.imshow('res_red1', res_red1)
res_red2 = cv2.bitwise_and(img, img, mask = mask_red2)
# cv2.imshow('res_red2', res_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)
# cv2.imshow('res_red', res_red)

img2 = np.zeros_like(img)

centroids, labels = cv2.connectedComponents(mask_red)

for i in range(centroids) :
    img2[labels == i] = [int(j) for j in np.random.randint(0, 255, 3)]

# numOfLabels, img_label, stats, centroids = cv2.connectedComponentsWithStats(mask_red)
# print(numOfLabels)
# print(img_label)
# print(stats)
# print(centroids)

# for idx, centroid in enumerate(centroids) :
#     if stats[idx][0] == 0 and stats[idx][1] == 0 :
#         continue
    
#     if np.any(np.isnan(centroid)) :
#         continue
    
#     x, y, w, h, area = stats[idx]
#     centerX, centerY = int(centroid[0]), int(centroid[1])

#     if area > 50 :
#         cv2.circle(img, (centerX, centerY), 10, (0, 0, 255), 10)
#         cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 255))

# cv2.imshow('res_blue', res_blue)
# cv2.imshow('res_green', res_green)
# cv2.imshow('res_yellow', res_yellow)
# cv2.imshow('res_red1', res_red1)
# cv2.imshow('res_red2', res_red2)
# cv2.imshow('res_red', res_red)

# cv2. imshow('img', img)
# cv2. imshow('img2', img2)

cv2.waitKey()
cv2.destroyAllWindows()

In [32]:
import cv2 # opencv 사용
import numpy as np

def region_of_interest(img, vertices, color3=(255,255,255), color1=255): # ROI 셋팅

    mask = np.zeros_like(img) # mask = img와 같은 크기의 빈 이미지
    
    if len(img.shape) > 2: # Color 이미지(3채널)라면 :
        color = color3
    else: # 흑백 이미지(1채널)라면 :
        color = color1
        
    # vertices에 정한 점들로 이뤄진 다각형부분(ROI 설정부분)을 color로 채움 
    cv2.fillPoly(mask, vertices, color)
    
    # 이미지와 color로 채워진 ROI를 합침
    ROI_image = cv2.bitwise_and(img, mask)
    return ROI_image

def mark_img(img, blue_threshold=200, green_threshold=200, red_threshold=200): # 흰색 차선 찾기

    #  BGR 제한 값
    bgr_threshold = [blue_threshold, green_threshold, red_threshold]

    # BGR 제한 값보다 작으면 검은색으로
    thresholds = (image[:,:,0] < bgr_threshold[0]) \
                | (image[:,:,1] < bgr_threshold[1]) \
                | (image[:,:,2] < bgr_threshold[2])
    mark[thresholds] = [0,0,0]
    return mark

image = cv2.imread('./sample3_515.jpg') # 이미지 읽기
height, width = image.shape[:2] # 이미지 높이, 너비

# 사다리꼴 모형의 Points
vertices = np.array([[(50,height),(width/2-45, height/2+60), (width/2+45, height/2+60), (width-50,height)]], dtype=np.int32)
roi_img = region_of_interest(image, vertices) # vertices에 정한 점들 기준으로 ROI 이미지 생성

mark = np.copy(roi_img) # roi_img 복사
mark = mark_img(roi_img) # 흰색 차선 찾기

cv2.imshow('roi_white',mark) # 흰색 차선 추출 결과 출력
cv2.imshow('result',image) # 이미지 출력
cv2.waitKey(0) 

32

In [ ]:
# 